### PR TITLE
Allow self augmentation if on morphine

### PR DESCRIPTION
**Pull request by Consul99**
## About The Pull Request
As the title says, a pretty small change. You can perform augmentation on yourself, however if you don't have morphine in your system you will always screw it up.

## Why It's Good For The Game
A pair of robos can already speed run augmentation in 5 minutes at the start of round. Not allowing self augmentation really only punishes lonely robos from being able to perform a core part of their gameplay loop.

As for powergamers, requiring morphine means a powergamer will need to get their hands on surgery tools, break into robo to get augmentation parts and chemistry to get morphine (or build their own machines), then, if they want it to actually be strong, break into nanites and program them without anyone noticing. At this point they could have obtained far stronger powergamer gear.

## Changelog
:cl:
tweak: self augmentation possible
balance: morphine necessary to succeed in self augmentation
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
not sure I agree with this, you say it's hard to powergame, but morphine is available in bottles from med storage, which is piss easy to get into and nobody will care that you're in there. also there's maint robo which can print parts

**Comment by Consul99** [comment]
> not sure I agree with this, you say it's hard to powergame, but morphine is available in bottles from med storage, which is piss easy to get into and nobody will care that you're in there. also there's maint robo which can print parts

I chose morphine because I think it's used 1 other place and seems thematically correct. However it can be changed to any other chemical very easily. Also my main point on powergaming is that unless you get nanites for it you only get a slight damage reduction and the ability to heal yourself in the field. You're also hella sus walking around as a metal man when you're not a roboticist.

**Comment by Consul99** [comment]
You're also very vulnerable to EMPs which are extremely easy to make in chem with some uranium and iron. There's also an EMP gun in security. So you're really only gimping yourself if you're trying to antag a metal man.

**Comment by PortableSeedExtractor** [comment]
merge this i want to powergame harder

**Comment by MCterra10** [comment]
Closed. The main argument for this is that augments aren't strong because of EMPs, but EMPs never stopped powergamers taking IPC, because they're relatively rare.
Full augments give a suite of benefits:
* Armour Increase
* Punch Immunity (Like Borgs)
* Easy Healing With Welder and Wire
* Spaceproof
* Ash Storm Immunity (Relevant for Miners)
I think making this easily available isn't a great change. Just ask someone else to do it for you. I don't think we should deliberately removing the small amount of player interaction we have.

**Pull request closed without merging**
