### PR TITLE
[Emotes] You can now say beans and cheese

### PR DESCRIPTION
**Pull request by thelaughingbomb**
## About The Pull Request

Beans and Cheese

## Why It's Good For The Game

whyiammakingthepr

## Changelog
:cl:
add: You can now *cheese and *beans
soundadd: beans.ogg
soundadd: cheese.ogg
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
Cheez

**Comment by TheFakeElon** [comment]
What if you made it chef only

**Comment by amidoingitright** [comment]
travis isn't fully greenlighting this, might wanna y'know make a new commit to force another check

**Comment by MCterra10** [comment]
cheese

**Pull request merged**
