### PR TITLE
[MIRROR] Pool party

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/3160
--------------------

## About The Pull Request

Ports the swimming pool from NSV.
Replaces the pool in the luxury shuttle with a real pool.
Replaces the pool in the hotel with a real pool.
Replaces the boxing arena on deltastation with a swimming pool.

Ports
https://github.com/BeeStation/NSV13/pull/781
https://github.com/BeeStation/NSV13/pull/824
https://github.com/BeeStation/NSV13/pull/840
 + Does a bit of mapping
 + Fixes some spelling mistakes and shitcode

Continuing the legacy of the cursed PR, to date every attempt at porting pools has failed.

## Why It's Good For The Game

Swimming is fun. Torturing felinids is fun.

## Changelog
:cl: PowerfulBacon, KMC, Cdey
add: Swimming pools
/:cl:

### CODE REVIEW

**Comment by Singularity69** [comment]
Beestation stealing all of our exclusive contents smh

**Comment by MCterra10** [comment]
it's fine it's from NSV
also needs austation map changes desperately

**Comment by MCterra10** [comment]
on hold pending removal of modularized pewls

**Comment by MCterra10** [comment]
oh and

**Comment by MCterra10** [comment]
domirror 3535

**Comment by MCterra10** [comment]
domirror 3205

**Comment by MCterra10** [comment]
domirror 3529

**Comment by MCterra10** [comment]
domirror 3512

**Comment by MCterra10** [comment]
domirror 3496

**Comment by MCterra10** [comment]
domirror 3204

**Comment by MCterra10** [comment]
domirror 3535

**Comment by MCterra10** [comment]
domirror 3070

**Comment by TheFakeElon** [comment]
dorime

**Comment by TheFakeElon** [comment]
merged #2999

**Pull request merged**
