### PR TITLE
Comments out all instances of integrated circuit code

### PR DESCRIPTION
**Pull request by Mick1299**
## About The Pull Request
Comments out all integrated circuit code, effectively removing it from the game/

## Why It's Good For The Game
Code is still there, it would all be easily re-enabled when someone decides to start balancing and maintaining them again.

## Changelog
:cl:
del: Removes integrated circuits
/:cl:

### CODE REVIEW

**Comment by MrLostman** [comment]
image
if this needs to be talked about can we do it in coder bus?

**Comment by TheFakeElon** [comment]
I ded

**Comment by MrLostman** [comment]
image

**Comment by MCterra10** [comment]
No spite PRs.
Ided

**Comment by MCterra10** [comment]
Also don't comment shit in the DME, ever.

**Comment by ZombiesVsPlants** [comment]
w e w

**Pull request closed without merging**
