### PR TITLE
Morphine Buff

### PR DESCRIPTION
**Pull request by MrLostman**
## About The Pull Request
Removes sedative effect from morphine.
Lowers metabolic rate to 0.25 from 0.5
Lowers the addiction and over dose to ~~10 and 15~~ 15 and 20 respectively.
Adds TRAIT_IGNOREDAMAGESLOWDOWN

## Why It's Good For The Game
this is a picture of morphine, the morphine is screaming, the morphine is flexing.

## Changelog
:cl:
balance: morphine sedative effect removed, meta rate 0.5->0.25 addiction and od reduced 25->15, 30->20, added no damage slow trait.
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
Morphine is a sedative though.

**Comment by MrLostman** [comment]
> 
> 
> Morphine is a sedative though.

image
I don't think it is and google agrees. Could still be wrong.

The IRL argument is weak anyway

**Comment by TheFakeElon** [comment]
@MrLostman Funnily enough, the google result is wrong. Morphine is an opiod that's used in hospitals for pain management and sedation.

**Comment by Ohagi-Chan** [comment]
I had to google it too, and apparently morphine is not a sedative.

**Comment by MrLostman** [comment]
I didn't remove it's sedative effect because it's not one IRL. There plenty of good toxins while this role for morphine is unique.

Like I said I find the IRL argument weak

**Review by MCterra10 — APPROVED** [review]
I like the painkiller usage. There's so much available in medbay and it's readily available in sleepers so it makes sense for this to be a painkiller rather than funny knockout drug.

**Comment by ZombiesVsPlants** [comment]
I worry slightly about the 10u overdose.

The sleeper injects 10u doesn't it?
Maybe change overdose to 15u and addiction to 20u?

**Comment by Ohagi-Chan** [comment]
> I worry slightly about the 10u overdose.
> 
> The sleeper injects 10u doesn't it?
> Maybe change overdose to 15u and addiction to 20u?

Oscar recently made a PR that prevents addiction/ overdose from occuring on the exact dosage.  You must now exceed the dosage to trigger effects.

**Pull request closed without merging**
