### PR TITLE
Decreases floor tile melting point

### PR DESCRIPTION
**Pull request by Mick1299**
## About The Pull Request
Reduces floor tile melting point to actual sane temperatures.

## Why It's Good For The Game
before #1830 , plasma fires would effectively self extinguish once they reached 10k. Kat's change increased that to 100k, temperatures rarely seen outside of urn chambers. This reduces the temperature to 50k, meaning we might occasionally see long burning plasma fires self regulate once again, and reinforced floors are no longer pointless outside of aesthetic.

If you don't want floors to melt, reinforce them. 

## Changelog
:cl:
tweak: Reduce floor tile burn temp to 50k
/:cl:

### CODE REVIEW

**Comment by ZombiesVsPlants** [comment]
Stop touching my plasmafires holodeck already got nerfed to shit.

**Comment by TheFakeElon** [comment]
we're lowpop, plasmafires bad

**Comment by ZombiesVsPlants** [comment]
Plasma flooding is one of the few tools left to a malf borgless ai, making it so it dissapears and can NEVER appear in that spot again (due to the hole) makes the jobs far harder (especially when the malf ai's job is literally to murder everyone half the time)

Malf ai is rare enough anyway that this doesn't occur often.

Plus if you're a malf borgless ai, you can't reinforce a floor in the first place.

**Comment by Mick1299** [comment]
I literally have no idea how you've managed to misconstrued the reason behind this into a malf ai nerf. 

Its not my problem if a malf ai doesn't have a shell, thats on them

**Comment by TheFakeElon** [comment]
this doesn’t make plasmafloods a while less deadly, it makes them function as intended. Plasma fires burning through fire immune hardsuits was an oversight from #1830

**Comment by totallynotkatfood** [comment]
40 pop is low?

**Pull request merged**
