### PR TITLE
[MIRROR] Ports Crew Transfer Vote from AuStation

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/1855
--------------------
## About The Pull Request
[issue link stripped] 
Ports the crew transfer vote from AuStation. I tweaked it slightly to allow the system to be enabled or disabled in the config. As per the feature request, the system is enabled by default on sage, and disabled on golden.
If you'd rather any of the messages or text to be changed, let me know.

## Why It's Good For The Game
Idk I just resolved the issue, but it's really handy on austation.

## Changelog
:cl:
add: Automatic Crew Transfer Vote for Sage
/:cl:

### CODE REVIEW

**Comment by coolsurf6** [comment]
pog

**Comment by MCterra10** [comment]
standby for demodularization

**Comment by MCterra10** [comment]
pending config changes

**Comment by MCterra10** [comment]
config updated

**Pull request merged**
