### PR TITLE
[MIRROR] Synthflesh recipe now has silver sulfadizine in it.

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/2411
--------------------
## About The Pull Request
Changes synthflesh recipe by adding silver sulfadizine to it in order to make synthflesh slightly harder to create.

## Why It's Good For The Game
Synthflesh is stupidly effective and has a very simple recipe, synthflesh recipe also has no chem in it that heals burn damage, only the styptic powder that heals brute damage.

## Changelog
:cl:
balance: Adds silver sulfadizine to synthflesh recipe.
/:cl:

### CODE REVIEW

**Comment by thelaughingbomb** [comment]
Damn

**Comment by coolsurf6** [comment]
Damn

**Comment by MCterra10** [comment]
Damn
I think I'm gonna get some opinions on this

**Comment by TheFakeElon** [comment]
it was way too easy to make an infinite synthflesh factory. It's not really fun to be a med doc when you have an infinite insta-heal dispenser that only takes around 10 minutes to setup, if that.

+1 from me

**Comment by jupyterkat** [comment]
If only there’s anyone around at all to make that factory, -1

**Comment by TheFakeElon** [comment]
I don’t play as much as I used to, but they are (were) common enough that it’d end up happening on _most_ rounds, I think a chem that can almost instantly heal the two most common types of damage should *at least* require one of each respective healing chem

**Comment by MCterra10** [comment]
Gonna agree with Doris, it kinda makes sense for it to be comprised of both chems
However cloning requiring synthflesh really sucks here, because no chemists really brew synthflesh specifically for that.
I might remove that requirement from cloning actually, it's just stupid and arbitrary imo

**Comment by coolsurf6** [comment]
Making synthflesh harder to make just means it might take just 5 more minutes t oget the factory going. Literally means nothing but I would still like to see it added WITH other changes. That change being synthflesh doing toxin damage based on how much it heals.

**Comment by TheFakeElon** [comment]
Yeah, there’s a PR upstream that’s nerfing the instant heal amount.

**Comment by MCterra10** [comment]
merging. I think this is an ok change. I am going to remove the synthflesh requirement for cloning though as a compromise.

**Pull request merged**
