### PR TITLE
Xenobiology Steroid crate

### PR DESCRIPTION
**Pull request by ZombiesVsPlants**
## About The Pull Request

Adds a crate
Xenobiology Slime Steroid crates for 2 slime steroids

## Why It's Good For The Game

Encourages inter-department cooperation without locking a necessary feature behind a paywall
Xenobiologists will be a lot better off with giving steroids to 3 slimes instead of the 20 slimes they will have by the time they get purples.

## Changelog
:cl:
add: adds Xenobiology steroids crate to cargo
/:cl:

### CODE REVIEW

**Comment by ZombiesVsPlants** [comment]
Bruh me retarded

**Comment by ZombiesVsPlants** [comment]
I think travis fucked up
>:(

**Comment by MCterra10** [comment]
bruh, this literally defeats the whole point of xenobio

**Comment by MCterra10** [comment]
what's the point of just being able to order slime mutation stuff without actually making them?

**Comment by ZombiesVsPlants** [comment]
what do you mean? these potions only enhance the xenobio's work

Theses are not SLIME MUTATION TOXINS
it is the slime mutation and stabilization stuff that changes the chance for a slime to mutate

**Comment by MCterra10** [comment]
so you're telling me, RD can waltz into cargo and buy up mutation potions to get rainbows 20 minutes into the shift? it's a no from me daug

**Comment by ZombiesVsPlants** [comment]
Removed the mutagen crate

**Comment by ZombiesVsPlants** [comment]
This better?

**Comment by MCterra10** [comment]
yeah

**Comment by ZombiesVsPlants** [comment]
cool!

**Comment by ZombiesVsPlants** [comment]
what do you think the prices for the 2 steroid potions should be?

**Comment by MrLostman** [comment]
Slime steroid potion are super nesh, to the point I have never used one. +1 extract when grinded is not very useful while I'm not against adding shit to cargo seems like something that doesn't have a use.

**Pull request merged**
