### PR TITLE
[Port] Rats Rats we are the rats!

### PR DESCRIPTION
**Pull request by thelaughingbomb**
## About The Pull Request

This is a port of https://github.com/tgstation/tgstation/pull/49884

## Why It's Good For The Game

More content for chefs and assistants. You can now raise rats by feeding them cheese wedges or promote them to a royal rat with royal cheese. Royal rats will poll the ghosts on creation so its a new ghost role too. Royal rats can create rats to protect them or roll the dice for coins or better yet, more cheese.
## Changelog
:cl:
add: Royal rats and royal cheese.
imageadd: The royal rats and royal cheese have their own sprites.
code: The code from the port was adjusted slightly to make them stronger by buffing their obj_damage to 21. They now gib on death to stop people from using abilities when dead.
map: Random maint spawn for royal cheese
/:cl:

### CODE REVIEW

**Comment by thelaughingbomb** [comment]
Ah good, it works this time.

**Comment by thelaughingbomb** [comment]
By the way, Obj_damage 21 is the minimum damage required to bust doors, the regal rat may be able to bust a door but it takes a while and they can still get shocked from it.

**Comment by thelaughingbomb** [comment]
What if i added a 1 in a mil chance for the royal rat to dig up a pulse rifle? 😳

**Comment by TheFakeElon** [comment]
> What if i added a 1 in a mil chance for the royal rat to dig up a pulse rifle? 😳

do it

**Comment by thelaughingbomb** [comment]
Ok

**Comment by ZombiesVsPlants** [comment]
bro we gotta e x p a n d  this list for gamer moments

**Comment by ZombiesVsPlants** [comment]
one in a million chance for a SM shard

**Comment by thelaughingbomb** [comment]
1 in a million chance for anti bread 😳

**Comment by MCterra10** [comment]
needs testmerge

**Comment by MCterra10** [comment]
is this done?

**Comment by MCterra10** [comment]
waiting

**Comment by MCterra10** [comment]
Ok, I'll do final review and merge when I'm home

**Review by MCterra10 — APPROVED** [review]
can't see anything obvious

**Pull request merged**
