### PR TITLE
browser passthrough second pass

### PR DESCRIPTION
**Pull request by Effectism**
the tgui bundle is getting changed like twice a day so I haven't built it just yet

## Changelog
:cl:
add: do spessman things while running around
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
bruh fix your travis issues

**Comment by MCterra10** [comment]
# "Please rebuild tgui."

**Comment by MCterra10** [comment]
also oh god I'm going to have to integrate some form of tgui automatic rebuilding if I merge this aren't I
fuck fuck fuck I didn't think of that oh fuck fuck

**Comment by MCterra10** [comment]
This is on hold while I look into adding some sort of continuous integration for tgui rebuilds

**Comment by MCterra10** [comment]
If I could recommend that you make this PR upstream on /tg/ so the changes filter down here and we can avoid conflicts, that would be great. It's going to take me some time to get CI for tgui rebuilds done, but I am getting there

**Comment by Effectism** [comment]
Will resolve conflicts when this is ready to merge

**Comment by Effectism** [comment]
Redundant as tg is also implementing passthrough.

**Comment by MCterra10** [comment]
roger that

**Pull request closed without merging**
