### PR TITLE
Fuel rod rework, depleted fuel and includes fix and more

### PR DESCRIPTION
**Pull request by TheFakeElon**
## About The Pull Request

Adds plutonium as a separate object rather than being an edited version of uranium. Reworks fuel rods code-wise to lay down the foundation for more nuclear content, also contains a few fixes/balances regarding tc rods

you can now sell plutonium rods via cargo. ss13 is now an enrichment center

also adds depleted fuel rods, A highly radioactive, non-fissible rod that you can make them by leaving a plutonium fuel rod in the reactor for ~33 minutes (yes not 100% accurate, might change in the future). 

RMBK can now go slightly more critical when certain gasses are introduced 

I will be giving plutonium and depleted rods a use in my next PR because muh atomization

also fixes austation includes, someone forgot the alphabet 

## Why It's Good For The Game

more nuclear content :) + code fixes and improves.

## Changelog
:cl:
add: Adds depleted fuel rods
add: Adds the ability to sell plutonium via cargo
balance: decreased the time it takes for telecrystal rods to fissile
fix: telecrystal rods now show the correct fissile percentage
code: Made plutonium it's own object
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
christ

**Comment by TheFakeElon** [comment]
mocha if you steal this I'm going to stab you with an insulin pen

**Comment by Moccha-Bee** [comment]
> mocha if you steal this I'm going to stab you with an insulin pen

i do not have a branch called "stolenfromfakeelon"

**Comment by TheFakeElon** [comment]
🔫

**Comment by TheFakeElon** [comment]
image

**Comment by Moccha-Bee** [comment]
beestation gang thanks you for the hostile take over of your code. 😳

**Comment by TheFakeElon** [comment]
time to stealthmerge all of my branches

**Pull request merged**
