### PR TITLE
Adds new borg sprites

### PR DESCRIPTION
**Pull request by totallynotkatfood**
## About The Pull Request

title

## Why It's Good For The Game

why not

## Changelog
:cl:
imageadd: Added borgs in skirts
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
wheeze

**Comment by totallynotkatfood** [comment]
oof

**Comment by MCterra10** [comment]
CI fail not your fault. Rerunning.

**Comment by ZombiesVsPlants** [comment]
Kat the fuck are you doing stop

**Comment by totallynotkatfood** [comment]
**no**

**Comment by ZombiesVsPlants** [comment]
Kat please I'm gonna get law 2'd into becoming skirt borg

**Comment by totallynotkatfood** [comment]
Added lights for them

**Comment by totallynotkatfood** [comment]
*wheeze*

**Comment by MCterra10** [comment]
is this ready yet?

**Comment by totallynotkatfood** [comment]
Yeah it is

**Comment by MCterra10** [comment]
alright this was hilarious, but I'm not actually merging the borg sprites further than a testmerge lmao

**Comment by MCterra10** [comment]
Payment received. Merging

**Comment by coolsurf6** [comment]
What the fuck is this PR

**Comment by coolsurf6** [comment]
I'm already too late, this PR is cursed

**Pull request merged**
