### PR TITLE
[MIRROR] fixes infinite holodeck scooters

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/4496
--------------------

## Why It's Good For The Game

[issue link stripped]

## Changelog
:cl:
fix: can't make scooters from holodeck skateboards anymore
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
remirror

**Comment by TheFakeElon** [comment]
mirror bot might have missed the holodeck PR

**Comment by TheFakeElon** [comment]
remirror

**Comment by MCterra10** [comment]
remirror

**Comment by MCterra10** [comment]
nah bot just didn't respond for some reason, weird

**Pull request merged**
