### PR TITLE
[MIRROR] Bridge and other high security areas now start with reinforced airlocks

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/2458
--------------------

## About The Pull Request

This PR changes all the bridge, head of staffs' office airlocks, EVA, teleporter and gateway to fully plasteel reinforced doors.
These doors take longer to hack and are not breakable with a fire axe. 

EDIT: Also the 2 walls in the little tunnel maint between cap's and the teleporter room on box is now reinforced walls instead of regular walls.

Note: this changes Box and Meta station. I will the rest of the maps if this gets merged.

## Why It's Good For The Game

Tiding is fun, but being the one getting tided isn't. This would theoretically give captain a bit more time to get his shit and leave or more time to call security over (if it exists) and prepare a defense against the AA rush, while also requiring a little bit more effort from the ones tiding (insuls are mandatory when trying to hack plasteel reinforced doors). 

## Changelog
:cl:
tweak: Airlocks to bridge and other high security areas such as the heads' offices, EVA, teleporter and gateway now start reinforced with plasteel.
/:cl:

### CODE REVIEW

**Comment by MrLostman** [comment]
I know this does not effect us but, classic bee

**Comment by MCterra10** [comment]
Lol imagine not banning people from rushing AA

**Comment by MCterra10** [comment]
do I mirror to austation?

**Comment by TheFakeElon** [comment]
As someone who has both mained and maimed assistant and head roles. I am deeply conflicted

**Comment by TheFakeElon** [comment]
Should we do a vote?

**Comment by jupyterkat** [comment]
this is why you break into engi to get insulated first

**Comment by TheFakeElon** [comment]
Insuls can't melt steel plates

**Comment by ZombiesVsPlants** [comment]
tbh bee moment

**Comment by ZombiesVsPlants** [comment]
wait a minute, doors harder to hack and more reinforced walls?
I smell ai buff smh merge now
/s

**Comment by MCterra10** [comment]
merging to austation

**Review by MCterra10 — APPROVED** [review]

**Comment by ZombiesVsPlants** [comment]
ai  b u f f e d

**Pull request merged**
