### PR TITLE
[MIRROR] [Ready]Ports Heretic from TGstation. Second attempt boys

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/2347
--------------------
About The Pull Request

Ports heretics from tg

I got really tired with coding for a while, but I'm back  ,and since im short on cash rn, why the fuck not.

@  me on coderbus or tg discord if you have any issues.
also adds support for pointed spells.
## Why It's Good For The Game

New antag good

[issue link stripped] 
## Changelog
:cl:
add: Ports Heretics from tg 
add: Support for pointed spells.
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
config updates @MCterra10

**Comment by thelaughingbomb** [comment]
Speeeeeeeedmerge

**Comment by MCterra10** [comment]
>81 changed files
>"speedmerge"
I don't think so, bucko

**Comment by thelaughingbomb** [comment]
I've play tested it if that means anything

**Comment by amidoingitright** [comment]
dont know if this is an issue but you can spen points on multiple paths

**Pull request merged**
