### PR TITLE
New roundend sound

### PR DESCRIPTION
**Pull request by mudzbe**
Christian asked for this to be PRed

:cl:
soundadd: New roundend sound
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
@MCterra10

**Review by MCterra10 — CHANGES_REQUESTED** [review]
Phantom changes from another PR. You've messed up your branches and made these changes on a branch with independent stuff (teleport sound)

**Comment by mudzbe** [comment]
what do

**Comment by mudzbe** [comment]
Oh shit cunt

**Comment by mudzbe** [comment]
damn

**Comment by mudzbe** [comment]
All g

**Comment by mudzbe** [comment]
@MCterra10 I fixed the phantom change/commit as per the request

**Comment by MCterra10** [comment]
thanks hun

**Review by MCterra10 — APPROVED** [review]

**Pull request merged**
