### PR TITLE
Moves the toxins tesing site away from the nuclear reactor.

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

title, also removed the unnecessary mixing tank console and added some cosmetics

## Why It's Good For The Game

maxcaps can fuck up the reactor if someone decides to use the site

## Changelog
:cl:
fix: moved the toxins tesing site away from the nuclear reactor.
/:cl:

### CODE REVIEW

**Comment by ZombiesVsPlants** [comment]
Thank god I'll stop being hit by quantum tunneled iron rods

**Comment by TheFakeElon** [comment]
> Thank god I'll stop being hit by quantum tunneled iron rods
 Nooo!

**Comment by TheFakeElon** [comment]
Could you post an image?

**Comment by jupyterkat** [comment]
image

**Review by TheFakeElon — APPROVED** [review]

**Comment by ZombiesVsPlants** [comment]
HA, long

**Comment by TheFakeElon** [comment]
_Its just as close to AI sat +1_

**Comment by ZombiesVsPlants** [comment]
if it ends up hitting the ai sat i'mma be sad

**Pull request merged**
