### PR TITLE
Felinids get cat-speak (again)

### PR DESCRIPTION
**Pull request by amidoingitright**
## About The Pull Request

dont even think about test merging this, its only been put up to assist with debugging

## Why It's Good For The Game

more felinid changes is good right?

## Changelog
:cl:
add: cat-speak, only synthetics and felinids can understand and talk this language
/:cl:

### CODE REVIEW

**Comment by amidoingitright** [comment]
As a reminder, while mergeable. I do not recommend this as there are a prevalent bug that i'm working to scrub out

**Comment by MCterra10** [comment]
no stop he's already dead!

**Comment by amidoingitright** [comment]
THE FUCKING FIX REQUIRES ME TO GO INTO BEESTATION CODE AND I DONT WANT TO TOUCH THAT, WHEN I TRY TO FIX IT FOR AN UPSTREAM MERGE IT KEEPS GIVING ME FILE PATH ERRORS SAYING THE FILE PATH ISN'T DEFINED AND I'M JUST SO GODDAMNED TIRED, HAVE FUN FIXING THIS BUSTED ASS PR ANYONE WHO WANTS TO PICK IT UP AGAIN

**Comment by amidoingitright** [comment]
yeah the only hope for this PR is if it gets done upstream

**Comment by totallynotkatfood** [comment]
mad?

**Comment by amidoingitright** [comment]
slightly, but atleast i'll be able to shit out a PR for bee

**Comment by coolsurf6** [comment]
I dout bee would touch a felinids pr change. Does bee even have felinids enabled? If they see that it is for one of their down syndrome servers, they miiiiiiight add it.

**Pull request closed without merging**
