### PR TITLE
[MIRROR] [PORT] TGUI 4.0, Smart Asset Caching, TGchat

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/2336
--------------------

## About The Pull Request

Ports:
https://github.com/tgstation/tgstation/pull/53026
https://github.com/tgstation/tgstation/pull/49982
https://github.com/tgstation/tgstation/pull/52947
https://github.com/tgstation/tgstation/pull/52321
https://github.com/tgstation/tgstation/pull/52323
https://github.com/tgstation/tgstation/pull/52408
https://github.com/tgstation/tgstation/pull/53075
https://github.com/tgstation/tgstation/pull/52280
https://github.com/tgstation/tgstation/pull/53012
https://github.com/tgstation/tgstation/pull/53141
https://github.com/tgstation/tgstation/pull/52233
https://github.com/tgstation/tgstation/pull/52681
https://github.com/tgstation/tgstation/pull/52426
https://github.com/tgstation/tgstation/pull/52085
https://github.com/tgstation/tgstation/pull/52955

Todo:
- [x] Port all the stuff on the project
- [x] Update our specific TGUI interfaces to TGUI 4.0
- [x] Update sending assets on all TGUI interfaces
- [ ] Final check all the ui_interacts to find where the script fucked up.
- [x] Fix asset_cache runtimes which fuck up all vending machines.

## Bee specific interfaces that need updating
- [x] AdminSecretsPanel
- [x] AdvancedAirlockController
- [x] TicketBroswer
- [x] TicketMessanger
- [x] Other stuff that I forgot about
- [x] May or may not have broken youtube.dll

## Why It's Good For The Game

Better loading or some shit, a chat system that is pretty easy to edit and has a lot of potential for formatting changes and looks great and some other stuff too.

## Btw for cooders

Your filepath to the files must NOT contain spaces otherwise asset transport breaks. If you load your .dme to compile your amazing code and all the vending machine icons are broken, remove spaces from your path to the .dme

## Important stuff for Downstreams

Other stuff:
Downstreams read this PR since it has important stuff on it that makes it actually work and stuff **https://github.com/tgstation/tgstation/pull/52681**

## Changelog MrStonedOne, StyleMistake
:cl:
refactor: Browser resources (images/css/javascript) will no longer be needlessly resent to all clients between rounds and reconnections
tweak: Reduced the number of single use html files saved to the Browser Resource folder (tmp12345) on player machines.
add: tgchat: Unread message count is now smarter and won't increase on other tabs if you have already read the same message in the active tab.
add: tgchat: Admin PMs are now properly annotated and can be filtered into separate tabs.
fix: tgchat: Fix: Highlighted message overlay no longer blocks clicks. Clicking a highlighted (F) link should work as it should.
fix: tgui: Fixed NTOS bluescreen due to calling .includes() on a stylesheet href which could be null on certain browsers.
code: tgchat: Chat schema bumped to version 5. All chat-related settings were reset to avoid breakage.
refactor: Interface assets (js/css/images) can now be managed using an external webserver instead of byond's one at a time file transfer queue.
admin: Adds admin verb toggle-cdn that allows admins to disable the external webserver asset transport and revert to the old system. Useful if the webserver backing this goes down (thanks cloudflare).
config: New config file, resources.txt, (must be loaded by an $include statement from the main config)
server: The external_rsc_urls.txt config has been moved to the main config system.
refactor: tgui windows should load faster after an initial load, if using the fancy mode. Please report any breakages.
/:cl:

### CODE REVIEW

**Comment by jupyterkat** [comment]
recoompile

**Comment by park66665** [comment]
It finally happened

**Comment by MCterra10** [comment]
oh fuckkk

**Comment by MCterra10** [comment]
remirror

**Review by MCterra10 — APPROVED** [review]

**Comment by MCterra10** [comment]
waiting on config changes

**Comment by MCterra10** [comment]
checks passed, attempting a testmerge.

**Comment by MCterra10** [comment]
resource webserver updated to take these new cached files.

**Pull request merged**
