### PR TITLE
[MIRROR] Mastermode is stored as a configuration entry

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/2982
--------------------

## Changelog
:cl:
config: Default gamemode is now a config entry.
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
conflicts with unmodular changes from #2614 @MCterra10

**Comment by MCterra10** [comment]
thanks @TheFakeElon

**Comment by MCterra10** [comment]
this is gonna fuck autosandbox hard
everything above 5 pop gonna be sekrit

**Comment by MCterra10** [comment]
may need to take the hit and comment the code. I like my default mode switching.

**Comment by MCterra10** [comment]
cheeky squash

**Comment by MCterra10** [comment]
cheeky no-commit revert with edits. keeping config .txt changes caus they're harmless and potentially sidestep conflicts down the road.

**Review by MCterra10 — APPROVED** [review]

**Pull request merged**
