### PR TITLE
wall slamming drops items now

### PR DESCRIPTION
**Pull request by thelaughingbomb**
## About The Pull Request
Makes confusion great again.

## Why It's Good For The Game
A simple knockdown isnt punishing enough.
## Changelog
:cl:
tweak: running into walls makes you drop items now
/:cl:

### CODE REVIEW

**Comment by coolsurf6** [comment]
Can we bass boost the sound of The table slamming?

**Comment by ZombiesVsPlants** [comment]
silicon buff

**Comment by ZombiesVsPlants** [comment]
Slam them into the wall with the force of 28 stab wounds

**Comment by TheFakeElon** [comment]
Cringe

**Comment by MCterra10** [comment]
god no, confusion is actually cancer

**Comment by thelaughingbomb** [comment]
Sad

**Pull request closed without merging**
