### PR TITLE
Adds a generic dexterous mob for admins to use

### PR DESCRIPTION
**Pull request by thelaughingbomb**
## About The Pull Request

So the only simple mob that is dexterous are gorillas and sentient gorillas are pretty OP. So this PR makes a new generic mob specifically for admins to edit with VV for their memes. Oh also they have the drone inventory system so they can wear things, not visible because no overlays, but they can be examined to see what they have equipped.

## Why It's Good For The Game

yes

## Changelog
:cl:
add: Added a generic mob
/:cl:

### CODE REVIEW

**Comment by coolsurf6** [comment]
Speedmerge

**Comment by thelaughingbomb** [comment]
I dont know what travis is on about. Its referencing a file that isnt being edited by this PR

**Comment by TheFakeElon** [comment]
travis you piece of shit

**Comment by MCterra10** [comment]
fix conflict

**Pull request merged**
