### PR TITLE
Meathook stunlock rebalance

### PR DESCRIPTION
**Pull request by Ohagi-Chan**
## About The Pull Request
Meathook nerf suggested by Alice, Kay and Nus.
Removes the hardstun applied by meathooks.
Does not affect the bounty hunter's meathook (which is weaker)
Meathook already ignores all armor, so unless I'm told to change this, it still will and you'll consistently get hit with the full 50 stam damage.

## Why It's Good For The Game
less stunlocking

## Changelog
:cl:
balance: meathooks no longer deal 25 brute
balance: meathooks no longer paralyze for 3 seconds
balance: meathooks now apply 50 stamina damage (ignores armor)
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
>less stunlocking
>50 stam damage

**Comment by Ohagi-Chan** [comment]
> > "less stunlocking"
> 
> > 50 stam damage

In fairness, 50 stam damage is much less than a 3 second hard stun, out of the box.
But, I have no real investment in this pr, I just made it at Nus/ Kay/ Alice's request.

I'll have them defend or negotiate such a number.

**Comment by Ohagi-Chan** [comment]
They don't seem interested in defending their request, they've all been warned, but nobody came to argue.

Closing pr.

**Comment by TheFakeElon** [comment]
@Ohagi-Chan Don't listen to ideasguys, they're not worth it 😆

**Pull request closed without merging**
