### PR TITLE
Radical Radials - pai holochassis

### PR DESCRIPTION
**Pull request by Mick1299**
## About The Pull Request
Another radical radial addition, this time pai chassis get some love

## Why It's Good For The Game
Another step on my journey to eliminate shitty input lists for things with primarily visual impact.

image

image

## Changelog
:cl:
tweak: pai holochassis selection process is now radial
/:cl:

### CODE REVIEW

**Comment by coolsurf6** [comment]
Actual pog. It is super cool how you are basically tgui-ing the selection UI of most elements. Screw all those white lists with a scroll bar!

**Comment by Mick1299** [comment]
Its a nice little project to brush up on my coding. I've got a whole list of things I want to eventually use radials for:
100%
>1. pda and id painting
>2. airlock painter
>3. holy book styles
>4. Cardboard cut outs
>5. Vending machine circuit board
>6. signs
>7. Canister styles
>8. clown, mime, and tiki mask style selection
>9. IPC screen icon and colour
>10. cyborg cable colour

Might also do
>1. hair and beard styles using mirrors, razors, and wig
>2. null rods
>3. Object skins
>4. paint
>5. Bar sign
>6. underwear, socks, shirts from dressers
>7. chameleon
>8. shape shifting

**Comment by Mick1299** [comment]
ah shit wait, this wasn't merged

**Comment by MCterra10** [comment]
Some things on the list I'd be opposed to, especially hair and IDs/PDAs, for a couple of reasons
a) it'll be clunky because there's so many choices
b) you can hit letter keys in lists to quick-skip to that section, it'll make it way harder to find what you want

**Pull request merged**
