### PR TITLE
AuStation piping update + minor fixes

### PR DESCRIPTION
**Pull request by Mick1299**
## About The Pull Request
Completely overhauls the piping for Austation, bringing waste and air distro lines onto one tile. 

Also includes a few minor map changes to bring Austation up to date with metastation.

## Why It's Good For The Game
Whats the point of having our own station if we don't make it our own. This pr makes the first major change to Austation, completely remapping the waste and air distro pipes onto one tile wide lanes.

Air pipes are now on layer 1, and waste pipes on layer 3. Layer 2 has been left for customisation, and local piping such as cryo, the SM, and toxins burn chamber.

Virology and Xenobiology satellites have been given a connection port to make refilling easier in the event of a breach. Ai sat has also been given an air tank and connection port, and a pump allowing it to be isolated from the stations air supply. 

Cleans up some maints wiring and disposals, nothing game changing.

Fixes a broken camera network in the incinerator, and adds an incinerator pump cam (props to @totallynotkatfood )

Have a glance at the map difference bot for a comprehensive overview of all changes.

## Changelog
:cl:
add: Completely remaps Austation air and waste piping
del: Removes shitty old layer 2 piping
fix: A handful of minor map errors
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
poggers in the chat

**Comment by Mick1299** [comment]
Everything functions when I run the station on a private server. Worth test merging to see how the station goes during normal rounds

**Comment by MCterra10** [comment]
unironically based

**Comment by MCterra10** [comment]
this is ready as far as I can tell. fullmerging.

**Pull request merged**
