### PR TITLE
Cat-ear tweak

### PR DESCRIPTION
**Pull request by amidoingitright**
@Coolsurf6 you are bad man, you drove me to this

## About The Pull Request

Coomsurf gay, security felinid now viable 

## Why It's Good For The Game

Felinid flashbang bullie sessions are now cancelled go home. (makes felinids who play security able to actually play security without getting flashbanged by both fellow sec, and people who somehow got flashbangs

## Changelog
:cl:
tweak: Changes cat ears bang protection from -2 to -1
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
I already blocked a PR that changed this from beestation lmao

**Comment by thelaughingbomb** [comment]
sec helmet plus ear muffs gives you +1 bang protection, enough to be able to survive a flashbang unharmed

**Comment by amidoingitright** [comment]
shame, real sahme

**Comment by coolsurf6** [comment]
Closet furry

**Pull request closed without merging**
