### PR TITLE
MK.I SWAT Armor Resprite

### PR DESCRIPTION
**Pull request by MrLostman**
image
image
🆑
tweak: new sprite for the mk.I swat armor
/🆑

### CODE REVIEW

**Comment by MCterra10** [comment]
Add a changelog, dumbass

**Comment by Effectism** [comment]
MrLostman: Rebase to oracle

**Comment by MrLostman** [comment]
Terra rebase to oracle.

**Comment by optimumtact** [comment]
Terra rebase to /tg/station

**Comment by MCterra10** [comment]
Not until you erase cobbychem, @optimumtact

**Comment by MCterra10** [comment]
🚨malformed changelog🚨 
use `:cl:` not the actual emoji or it doesn't work

**Pull request merged**
