### PR TITLE
[MIRROR] Ports tgchat sanitization

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/3381
--------------------

## About The Pull Request

Ports tgstation/tgstation#56001

## Why It's Good For The Game

css fuckery bad

## Changelog
:cl:LemonInTheDark
admin: Chat messages that are more then text, so videos, embedded games, font changes, etc now get wiped when the chat is reloaded
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
remirror

**Comment by TheFakeElon** [comment]
remirror

**Comment by jupyterkat** [comment]
you’d have to rebuild tgui for this

**Comment by TheFakeElon** [comment]
@jupyterkat I know how TGUI works -_-

**Comment by MCterra10** [comment]
lint failing because of tgui changes. ignoring

**Pull request merged**
