### PR TITLE
[MIRROR] arts & canvases update

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/5431
--------------------

## About The Pull Request

tgstation/tgstation#48834
tgstation/tgstation#53585
tgstation/tgstation#56349
tgstation/tgstation#53994
tgstation/tgstation#59146
and multiple supporting loose commits

reeeeee

## Why It's Good For The Game

artss

## Changelog
:cl: tralezab, AnturK
add: curators can now print paintings
add: persistent paintings
add: AIs can now pick paintings as their screens
add: tgui canvases
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
remirror

**Comment by TheFakeElon** [comment]
ahh map conflicts, lovely

**Comment by MCterra10** [comment]
nah just needs austation map updates

**Comment by MCterra10** [comment]
remirror

**Pull request merged**
