### PR TITLE
[MIRROR] Getting robusted by the cat surgeon is a fate worse than death

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/1447
--------------------
## About The Pull Request

Instead of killing you, the cat surgeon(an npc found in a space ruin) will replace your ears with cat ears, and give you a cat tail. He will then pacify you and heal you.
The cat surgeon is also now equipped with a syringe gun, with which he can shoot syringes of 7u morphine
image

## Why It's Good For The Game

I'm not sure if it is, to be honest. This is truly a fate worse than death for spacefaring travellers

## Changelog
:cl:
add: the cat surgeon in space will try to knock you unconscious with morphine and his saw. and, when he gets you unconscious, he'll give you cat ears and a tail, before pacifying you.
imageadd: Cat Surgeon now has a syringe gun
/:cl:

### CODE REVIEW

**Comment by coolsurf6** [comment]
I literally logged in just to say this is a cursed PR. Do we really need to gey it added?

**Comment by zeskorion** [comment]
> I literally logged in just to say this is a cursed PR. Do we really need to gey it added?

I do not think terra will merge this cursed code i made in a feverish fey mood one late night, lucky for you

**Comment by MCterra10** [comment]
pending CI

**Comment by MCterra10** [comment]
To clarify, I'm letting it keep the syringe gun, I think the stun thing is cool, but this mob is the CAT BUTCHER, it's designed to rip the tails off catgirls, not sew them on.

**Pull request merged**
