### PR TITLE
[MIRROR] Adds pensive

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/2870
--------------------

## About The Pull Request

Pensive

## Why It's Good For The Game

Pensive

## Changelog
:cl:
add: :pensive:
/:cl:

### CODE REVIEW

**Comment by amidoingitright** [comment]
No files changed 😔

**Comment by TheFakeElon** [comment]
remirror

**Comment by MCterra10** [comment]
that's... weird, I'll look into it later

**Comment by TheFakeElon** [comment]
😔

**Review by MCterra10 — APPROVED** [review]

**Comment by TheFakeElon** [comment]
🙏

**Pull request merged**
