### PR TITLE
[MIRROR] [Bounty] tgui: Version 3

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/1623
--------------------
## About The Pull Request

Ported nearly all UIs to the newest tgui framework.

Read this PR to see what's new in tgui v3: https://github.com/tgstation/tgstation/pull/50497

Unique BeeStation UIs were ported to tgui v3 as well: BottleDispenser, PatchDispenser, TurboLift.

I've done some preliminary testing, and a lot of things seem to work!

image
image

## What was not ported

I will most probably not port these UIs as part of this PR and bounty.

- Achievements (it's a lot more than just UI, and you don't have them)
- MedicalKiosk (is being ported by some other guy)
- RemoteRobotControl (Something fucky, don't remember what exactly)
- Bepis (New science machinery and additional content)
- BlackMarketUplink (Completely new item and additional content)
- VaultController (KS13 derelict)
- DnaConsole (It's fukken MASSIVE! https://github.com/tgstation/tgstation/pull/50225)
- NtosShipping (Shipment barcodes)
- Electrolyzer (Hydrogen gas)
- Roulette (apparently you deleted roulette in your codebase)
- MalfunctionModulePicker
- Gateway (touches a lot of files, very hard to port)

Some UIs were cut down to avoid some expensive work:

- NtosArcade
  - Doesn't print tickets which you redeem in the arcade machine.
  - Doesn't level your gamer skills.

Clockwork cult was deleted long time ago in tg, so no UI was ever made for it. I recommend removing this game mode completely.

## TODO

- [x] Include changes from this PR: https://github.com/tgstation/tgstation/pull/50613
- [x] ~~Fix maps: `snowdin.dmm:2907:error: undefined type: /obj/machinery/gateway/centeraway`~~

## Why It's Good For The Game

TGUI 3.0 is significantly faster than old tgui, easier to develop for, and looks better.

**TGUI v2 (tgui-next) and TGUI v1 (ract) are GONE!**

image

## Changelog
:cl:
add: added tgui version 3.
add: lots of new fancy interfaces to discover!
add: check out the new camera console and your modular tablets for cool apps!
/:cl:

### CODE REVIEW

**Comment by coolsurf6** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.

More tgui is definitely a welcome change.

**Comment by MCterra10** [comment]
getting some line ending conflicts. will have to pull the pr down and fix

**Comment by MCterra10** [comment]
def going to need a testmerge to make sure this works

**Comment by MCterra10** [comment]
uh oh

**Comment by coolsurf6** [comment]
Uhhhh...

**Comment by MCterra10** [comment]
who tf uses CRLF as line endings on github? someone who needs a smack to the face no doubt

**Comment by MCterra10** [comment]
merging after CI

**Pull request merged**
