### PR TITLE
Removes SMES buffer from the powernet

### PR DESCRIPTION
**Pull request by Ohagi-Chan**
## About The Pull Request
Removes the SMES buffer from roundstart AuStation.dm, requiring engineers to actively set up a buffer of their own if they want to protect the station from power outages.

The station still has 4.5e6 joules in reserve, so the time before the first blackout is unchanged, but should the SM (and solars and whatever else) stop running, the station will immediately blackout.  Areas with their own SMES are protected from this.

Finally, the emitters now have their own SMES that will provide them with 40KW even if the rest of the station runs out of power.  The emitter SMES is charged by the station's powernet but does not give anything back to it.

## Why It's Good For The Game
Makes engineers work harder to provide a safe station to the masses.
It's a buff because now the emitters won't run out of power just because nobody set up.
It's a nerf because engineers now have to add a terminal and feed to the remaining old SMES if they want the station protected against blackouts when the SM is turned off.

## Changelog
:cl:
add: a new SMES to the emitter room, east of the SM
del: removed 2 of the SMES from the power monitoring room
del: removed the terminal attached to remaining SMES in the power monitoring room
tweak: changed the layout of cables connecting the SM to the main grid, now the SM is plugged straight in
tweak: changed the default charge of the remaining SMES in the power monitoring room - now it has 3x the charge
/:cl:

### CODE REVIEW

**Comment by totallynotkatfood** [comment]
oh lord the file changes

**Comment by Ohagi-Chan** [comment]
> oh lord the file changes

my first ever attempt at using github to pr.  help appreciated.

**Comment by thelaughingbomb** [comment]
You gotta update your master on your branch

**Comment by Ohagi-Chan** [comment]
> You gotta update your master on your branch

might need some help with that.
I tried pressing every damned button that said pull or fetch and the branch remained 85 commits behind, but claimed that it was up to date.

**Pull request closed without merging**
