### PR TITLE
Slippery cyborgs!

### PR DESCRIPTION
**Pull request by TheFakeElon**
## About The Pull Request

cyborgs can now slip!

## Why It's Good For The Game

slip!
rip janny borgs lmao

## Changelog
:cl:
balance: cyborgs can now slip over
/:cl:

### CODE REVIEW

**Comment by Mick1299** [comment]
Modularise it bruh

**Comment by TheFakeElon** [comment]
(it was a meme PR)

**Comment by Mick1299** [comment]
sad, that would have been funny

**Comment by zeskorion** [comment]
>closing meme prs instead of letting them get merged


you have a lot to learn

**Comment by TheFakeElon** [comment]
wrong button lol

**Comment by ZombiesVsPlants** [comment]
: (

**Comment by MCterra10** [comment]
sowwy elon

**Pull request closed without merging**
