### PR TITLE
You can now make furniture out of human leather

### PR DESCRIPTION
**Pull request by thelaughingbomb**
## About The Pull Request

It does exactly what it says on the tin

## Why It's Good For The Game

You can now turn those pesky humemes into a nice recliner or a table to support your war crimes

hmm

## Changelog
:cl:
add: you can now make a chair or a table out of human leather
/:cl:

### CODE REVIEW

**Comment by thelaughingbomb** [comment]
thanks travis

**Comment by thelaughingbomb** [comment]
Currently you build chairs by interacting with human hide in your hand and tables are made like any other table, apply leather to table frame.

**Comment by TheFakeElon** [comment]
Moth and lizard tables when

**Comment by thelaughingbomb** [comment]
When you sprite / code it

**Comment by thelaughingbomb** [comment]
The mad lad actually merged my shitpost

**Pull request merged**
