### PR TITLE
[MIRROR] Removes the bluespace miner

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/5071
--------------------

## About The Pull Request

Removes the bluespace miner and any references to it.

## Why It's Good For The Game

There is no more golden, these just exist for no reason.

## Changelog
:cl:
del: Removed bluespace miners from config and game
/:cl:

### CODE REVIEW

**Comment by Singularity69** [comment]
No, we are golden replacement

**Comment by YakiAttaki** [comment]
Absolutely not.

**Comment by Sychtal** [comment]
good thing we're a lrp server so there's no reason to remove them right?
right?

**Comment by lordScrubling** [comment]
if you guys never merged their removal from research then you won't need to worry

**Review by MCterra10 — APPROVED** [review]
configuration has been updated

**Pull request merged**
