### PR TITLE
Public mining

### PR DESCRIPTION
**Pull request by Ohagi-Chan**
## About The Pull Request
Adds a public mining shuttle to Austation and the lavaland map, allowing the public to access some of the lavaland mining base without miner-level access.

## Why It's Good For The Game
Gives the station the opportunity to send staff to lavaland to collect materials if no miners are present.
Gives antags a more viable way to intercept miner targets.

## Changelog
:cl:
add: metastation public mining shuttle from TG
add: public mining console
add: public mining console computer board
add: a new lavaland map to be used with PM compliant stations
tweak: replaces Austation arrivals lounge with a shuttle dock
/:cl:

ToDo
- [ ] add the station-side mining dock
- [ ] work out how to force Austation/Lavaland when Austation is chosen
- [ ] make all stations public mining compliant if that fails

### CODE REVIEW

**Comment by Ohagi-Chan** [comment]
I don't think I'm able to make this work with my own abilities. Closing.

**Comment by coolsurf6** [comment]
Please do actually get this working. I assume you will have to talk with mick or someone who knows how to deal with map merging. This would be cool to have!

**Comment by Ohagi-Chan** [comment]
Sorry coolsurf.
Having some issues that weren't present yesterday, but I will try to get this draft back into a state where MapMerge can generate a preview of my maps again.
I'd love if they at least were later used by a better coder to make this project a reality, but I don't believe I'm the one to do it.

**Comment by TheFakeElon** [comment]
sooo many conflicts

**Comment by coolsurf6** [comment]
Look at all those conflicts.

**Pull request closed without merging**
