### PR TITLE
Plasmeme command helmets buff

### PR DESCRIPTION
**Pull request by LastCrusader105**
## About The Pull Request

Adds the buffs of the hardsuit HELMETS to plasmeme versions e.g CAPs helmet is now tempproof acid proof and provides a small brute buff etc

## Why It's Good For The Game

why should a plasmeme head of staff be held back by his helmet, yes they now have a slight buff when they arnt wearing the hardsuit but thats only to the head, i personally feel its not a big issue, plasmemes weak and sow as is

image of plasmemes wearing helmets and not burning (note the R&D has the research scanner attached to his helmet like the hardsuit version)
image

each head and atmos tech wearing helmet and their normal outfit and a copy wearing hardsuit
image

the aftermath
image

humans in hos and cmo suits
image

again please forgive fact images arnt of your server, but same codebase, also includes stamina stats

## Changelog
:cl:
balance: added hardsuit helmet buffs to Plasmeme head of staffs helmets
fix: fixed atmos plasmeme helmet not being heat proof
/:cl:

### CODE REVIEW

**Comment by LastCrusader105** [comment]
opps added box

**Comment by Dawson1917** [comment]
Not being able to put on some equipment is part of nonhuman species' downsides. It gives something for other players to take advantage of when they're planning to kill you, in this case the fact that your envirosuit helmet isn't protective. Giving special equipment to alleviate species downsides makes them less distinctive from humans

**Comment by LastCrusader105** [comment]
> Not being able to put on some equipment is part of nonhuman species' downsides. It gives something for other players to take advantage of when they're planning to kill you, in this case the fact that your envirosuit helmet isn't protective. Giving special equipment to alleviate species downsides makes them less distinctive from humans

I understand your point and agree they need to have disadvantages as well as advantages, but disagree this is "special equipment" based on the following
but id say this case it was a coders oversight, the CE helmet isnt heatproof, centcoom sent their plasmeme head of engineering with a plastic helmet
but its more about the look of it, without the look of the plasmeme whats the point of being one
same as moth, cat person and lizard without their tails or wings etc they are just human

i dont think its a species issue cause if that was case i wouldnt be able to wear the hardsuit helmet,

**Comment by TheFakeElon** [comment]
Plasmeme is already one of the more positive non-human races. Being able to perform engineering and medical objectively better in many scenarios.

You can justify almost every non-hardcoded race downside as an "oversight" if you stretch it enough. Plasma men have more than enough going for them already. I don't think they need anything more. Helmets are supposed to be one of their downsides 😆

**Pull request closed without merging**
