### PR TITLE
Bruh moment [Meme PR]

### PR DESCRIPTION
**Pull request by thelaughingbomb**
## About The Pull Request

Lets you *bruh

## Why It's Good For The Game

You can now *bruh at a bruh moment

## Changelog
:cl:
add: *bruh emote
soundadd: bruh.ogg
/:cl:

### CODE REVIEW

**Comment by coolsurf6** [comment]
Bruh

**Comment by thelaughingbomb** [comment]
bruh

**Comment by thelaughingbomb** [comment]
Think ill wait for this PR before trying to make another PR

**Comment by MCterra10** [comment]
oof that was a mistake

**Comment by MCterra10** [comment]
resolve your merge conflicts though @thelaughingbomb

**Comment by MCterra10** [comment]
I'd recommend you move Yaki's emote code from their file to your own file since theirs should have been under human emotes, not general emotes. Then just remove yaki's file and remove it from the includes

**Pull request merged**
