### PR TITLE
new aussie drinks!

### PR DESCRIPTION
**Pull request by TheFakeElon**
## About The Pull Request

Adds:
Ginger Beer. why was this not here before
jägermeister. not Australian but needed for the next
jäger_bomb_. Australian, a drink that acts like Amanitin but explodes instead of dealing tox
bushranger. Australian duh, gives stamcrit, sleep and damage slowdown immunity while also providing psychotic brawling

## Why It's Good For The Game

A: moar Australia

B: bartender doesn't have a lot going for them drink wise at the moment, they have some _okay_ chemicals like neurotoxin and bacchus. jägerbomb is also good for spiking drinks due to it's delayed "effect"

## Changelog
:cl:
add: ginger beer
add: jägermeister drink
add: jägerbomb. bartender exclusive explosive
add: bushranger drink. weaker, more aussie version of bathsalts
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
I might add an effect to bushranger

**Comment by ZombiesVsPlants** [comment]
extra punch force

**Comment by Ohagi-Chan** [comment]
Delayed effects good.  I wish there were more.

**Comment by zeskorion** [comment]
Jagerbomb should check if it was taken via ingestion

**Comment by TheFakeElon** [comment]
_**no**_

**Comment by YakiAttaki** [comment]
ginger beer sucks why'd you add it

**Comment by Mick1299** [comment]
Ginger beer should slightly heal your stomach

**Comment by amidoingitright** [comment]
Ginger beer is based

**Comment by TheFakeElon** [comment]
speedmerge:tm:

**Comment by MCterra10** [comment]
Done?

**Comment by TheFakeElon** [comment]
> Done?

Yep!

**Pull request merged**
