### PR TITLE
Adds a plumbing area to austation

### PR DESCRIPTION
**Pull request by thelaughingbomb**
## About The Pull Request

Title
## Why It's Good For The Game

There is no dedicated plumbing area on austation, now there is.

plumbing

## Changelog
:cl:
add: Plumbing area to austation
/:cl:

### CODE REVIEW

**Comment by thelaughingbomb** [comment]
Am i doing this right?

**Comment by Mick1299** [comment]
Yep, all worked perfectly.

Only three things, and they're all the same thing. The weird window looking into the chapel, the weird window looking into the viro break room, and the lower half of the viro glass corridor is still glass.

Apart from that, I don't 100% agree with the placement, it sort of just feel slapped there...But it does work.

**Comment by thelaughingbomb** [comment]
I decided on that placement since it was just empty space.... I didnt want to renovate a large portion of medical to fit a empty room in.

**Comment by thelaughingbomb** [comment]
Do not merge until i resolve issues

**Comment by TheFakeElon** [comment]
fix maint lol

**Comment by MCterra10** [comment]
^yeah, make that small section of maint medical themed

**Comment by thelaughingbomb** [comment]
I think i got all the issues

**Comment by Mick1299** [comment]
Can you modularise the area file, it would be helpful if we add any custom areas to our own map

**Comment by thelaughingbomb** [comment]
Yeah, i didnt even considering of modularising the file when i made it... would be a decent way to avoid any potential conflicts when upstream decides to add new areas too.

**Comment by thelaughingbomb** [comment]
ah my includes isnt upto date...

**Comment by thelaughingbomb** [comment]
Includes updated

**Comment by thelaughingbomb** [comment]
Every thing should updated now

**Comment by MCterra10** [comment]
seems ok

**Pull request merged**
