### PR TITLE
[Testmerge only] Cramstation 

### PR DESCRIPTION
**Pull request by Effectism**
move aside ministation

### CODE REVIEW

**Comment by MCterra10** [comment]
very cool

**Comment by MCterra10** [comment]
needs config update, not testmerging until I do that

**Comment by MCterra10** [comment]
updating config, ready to testmerge

**Comment by Effectism** [comment]
why has god abandoned us

**Comment by MCterra10** [comment]
We done with this now?

**Comment by Effectism** [comment]
Yep, good to close now/

**Pull request closed without merging**
