### PR TITLE
[MIRROR] Add moth plush

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/2454
--------------------
https://github.com/tgstation/tgstation/pull/49732, 46062, and 49878

## About this PR

Adds moth plushie and it's respective suicide act

:cl: ATHATH, ArcaneDefence
add: Moth plushie, found in arcade machines as a reward. Commiting suicide with it is ill advised.
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
remirror

**Comment by jbox144** [comment]
speedmerge

**Comment by TheFakeElon** [comment]
remirror

**Comment by amidoingitright** [comment]
A plush that eats your soul

**Comment by TheFakeElon** [comment]
remirror

**Pull request merged**
