### PR TITLE
FAIR BALANCE

### PR DESCRIPTION
**Pull request by mudzbe**
## About The Pull Request

Basically the pandora is HOT GARBAGE, so I buffed it's health by a third, slightly increased it's move speed and buffed it's melee damage. (15? 15? really 15 is the most this slow ass bitch ass cube can do? c'mon)

## Why It's Good For The Game

I̶ ̶d̶i̶e̶d̶ ̶a̶n̶d̶ ̶i̶t̶ ̶w̶a̶s̶ ̶u̶n̶f̶a̶i̶r̶ ̶a̶n̶d̶ ̶n̶o̶w̶ ̶I̶ ̶w̶a̶n̶t̶ ̶r̶e̶v̶e̶n̶g̶e̶

## Changelog
:cl:
balance: Buffed the Pandora elite mob
/:cl:

### CODE REVIEW

**Comment by jupyterkat** [comment]
Ided moment

**Comment by ZombiesVsPlants** [comment]
He speaks the words of gods!

**Comment by TheFakeElon** [comment]
Increasing the speed var decreases how fast they can move.
Don't ask why

**Comment by mudzbe** [comment]
I call admins Kiarra and host Terra to the stand, to testify on the effectiveness of this shit cube

**Comment by amidoingitright** [comment]
and the only thing left in pandora's box was hope, and hope remained in their house forever

**Comment by mudzbe** [comment]
eh

**Comment by MCterra10** [comment]
eh

**Comment by MCterra10** [comment]
honestly even sentient elites aren't really a match for any miner worth their salt. they just can't move fast enough to stay out of KA. Goliath is probably the only one that actually has a chance.

**Comment by mudzbe** [comment]
why not might do something later

**Comment by mudzbe** [comment]
For real

**Pull request closed without merging**
