### PR TITLE
[MIRROR] Apids (Bee People) Approved™ Pectoral Edition

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/1571
--------------------

## About The Pull Request

This PR introduces a new playable humanoid race, Apids, bee people in other words.

image

## Why It's Good For The Game

It gives the player more options to play as, and well, I mean, we're on BeeStation. This'll probably get replaced with a more in-depth reason as soon as I can get the opinions of some folk regarding certain ideas. It also replaces flypeople, who while cool, didn't really have anything majorly game-changing about them, as a selectable race.

## Changelog
:cl:
add: Added apids, also known as bee people.
add: Added a whole lot of shit related to apids.
/:cl:

## Done, but will probably need fixing-up and such

- Existence
- Take more damage to flyswatters
- Take more damage to pestkillers
- Can breathe in pressures of 8kPA thanks to the many spiracles in their body (bullshit).
- The Apidite language, consisting of one syllable: Bzz.
- Apid Wings that permanently take up your neck slot and allow you to dash forward 4 tiles.
- Take twice as much heat, cold, burn, and stamina damage.
- Roundstart enablement with disablement of flypeople.

## Future

- Adds the apid stinger - A stinger that upon stinging, injects 5u of Toxins every second it remains embedded. If the stung person moves, the stinger and liver of the apid gets removed. If the apid moves, the apid takes 30 brute damage and the stung person 20. Only careful yanking-out works as the non-harmful way to remove it.
- Get high off smoke.

## Possible Ideas
- Apid comradeship with bees, aka summoning bees from REASONABLY nearby beehives to maybe heal you or help you bash in the skull of an assistant.
- Have hornet people be the ash-walkers of the jungle, if that ever happens.

## Credits

- thatguythere03 for spriting the bodyparts and suggestions
- Ayy-Robotics, Emotions, Dekunutkid, for suggestions in Discord.
- The rest of BeeStation's Discord, for suggestions and somewhat support.

### CODE REVIEW

**Comment by MCterra10** [comment]
wtf

**Comment by MCterra10** [comment]
this is so much powercreep. I'm disabling this in config until some balance PRs go through. Wings should take up backpack slot/limit to messenger bags

**Comment by coolsurf6** [comment]
I think making the dash have a high cooldown and maybe even give 10 stamina damage on use for a while would be good. Or change the stamina to 50 to have a 100% chance to slow down the character, although that might be a bit too much.

These are actually kinda cool.

**Comment by coolsurf6** [comment]
Also taking up bag slot sounds cool

#FuckBagGang

**Comment by MCterra10** [comment]
I'm going to merge this, but just have them disabled roundstart for now, because I want to clear the backlog of related PRs

**Comment by coolsurf6** [comment]
👌

**Pull request merged**
