### PR TITLE
[MIRROR] Replaces remnants of old firelocks on most maps

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/3414
--------------------

## About The Pull Request

Title. Includes Pubby, Delta and Meta. Also [issue link stripped] 

## Why It's Good For The Game

Firelocks are consistent

## Changelog
:cl:
tweak: Replaced most instances of old firelocks
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
metastation changes

**Comment by TheFakeElon** [comment]
@Ohagi-Chan, if you wanted to do this

**Comment by Ohagi-Chan** [comment]
> @Ohagi-Chan, if you wanted to do this

Sure.
Is there a way for me to get an email for prs matching the map edit tag?

**Comment by TheFakeElon** [comment]
#2958

**Pull request merged**
