### PR TITLE
[MIRROR] Shotgun rebalance

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/2402
--------------------

## About The Pull Request
Alternate to #2396 and #2397

Shotguns have been changed in three ways: sprites, fire rate and ammo.

**Sprites**
New sprites for holding shotguns inhand as well as on your back. This makes them more obvious, rather than blindly walking into a world of pain.

**Fire rate**
Riot shotguns have a slightly slower fire rate, and combat shotguns have a slightly faster one.

**Ammo**
Lethal ammo is slightly weaker. Slugs now do 5 less damage and have -10 armour penetration (armour matters slightly more now). Buckshot now deals 66 brute damage total (down from 75) against unarmoured targets and have -10 armour penetration.

## Why It's Good For The Game
Shotguns are quite powerful weapons so this makes them slightly worse across the board rather than going for a huge nerf like making lethal ammo virtually inaccessible. 

## Changelog
:cl:
balance: Shotguns have new, bigger sprites for inhands and back slot.
/:cl:

Ports:
https://github.com/tgstation/tgstation/pull/45521
https://github.com/tgstation/tgstation/pull/47472
https://github.com/tgstation/tgstation/pull/52390

### CODE REVIEW

**Comment by MrLostman** [comment]
image
oh good thats burns my eyes

**Comment by TheFakeElon** [comment]
🤮

**Comment by TheFakeElon** [comment]
Shotgun nerf is needed but my god these sprites. They’re not even holding them properly

**Comment by ZombiesVsPlants** [comment]
funnily enough, this is JUST a resprite the changes were removed from the original PR but the description and changelog weren't updated.

**Comment by ZombiesVsPlants** [comment]
Screen Shot 2020-10-14 at 10 13 14 am

**Comment by ZombiesVsPlants** [comment]
Screen Shot 2020-10-14 at 10 14 18 am
PFT
Zesk moment

**Comment by TheFakeElon** [comment]
Oh you’ve got to be shitting me

**Comment by TheFakeElon** [comment]
remirror

**Comment by MCterra10** [comment]
why is zesko unironically such a nuisance to work with

**Pull request merged**
