### PR TITLE
New Gamemode - Siege

### PR DESCRIPTION
**Pull request by mudzbe**
## About The Pull Request

Siege starts with a few antags with the objective of mincing the station and racking up the body count. At the start of the round, the crew is informed of their impending doom and is tasked with creating as much gamer gear as possible, naturally the antags are present so this process must be tempered to prevent WMDs from falling into the antag's hands. They have no TC, but are fitted with Bloodbrother radios, so must work as a team. After an hour the nukeop's shuttle arrives but the nuke is replaced with a spawner. Ghosts can spawn as several unique classes with the aim of destroying the station/killing the crew. The ghosts are given 3 options, after a period of time (20 minutes?), elite classes are added to the pool of selectable, there is a 15% chance of having this option. There is a 10 minute respawn cooldown (from spawn). The nukeop's shuttle has buffed turrets and the normal entrance is impassible by crew.

Attackers can arm and defenders disarm the nuke with the disc, this prevents the round from dragging on and gives a central focus to both teams. This can naturally be moved by admins, or otherwise stay in the vault.

The first half of this gamemode plays like a traditional round, except antags are given no limits to their destructions, further they should work as a team. They have two challenge; acquiring combat gear and avoiding getting decimated by the souped up valid hunters. Acquiring combat gear is not as hard as normal as that is what everyone is doing, this gives them a level of plausible deniability, especially when working as a team. But teamwork is crucial as everyone is stacked and on a hair trigger. After the bodycount is racked up and defences somewhat sabotaged, those killed in the first stage spawn as the attackers - this prevents that team being too weak initially. The second half is what the first was building up to, a reason to acquire gamer gear and a thing to use it on. There is also an element of competition here where you see how long you can last.

The syndicates have access to the normal nukie gear on the shuttle, some bombs and syndie suits. Admins can choose to move the shuttle away from the syndie base to prevent them from getting that gear. The standard classes have about 15tc worth of gear.

The engineer can build a turret teleporter and dispenser. The dispenser supplies bullets, armour and an energycore which fully recharges a energy gun but also disappears after a short period of time.

The classes are:
[Class Template] - Syndie uniform, space suit, antidrop implant, dusts on death, combat knife
Engineer - Shotgun, Syndi PDA which can construct a turret, quantum pads, and a dispenser which supplies ammo, 50 metal
Specialist - 12 TC uplink (Change?)
Pirate - 2 laser guns, c4, x4, pirate uniform, is a skeleton (space immune)
Grunt - .45 SMG - 4+1 mags
Zombie - Romerol zombie (doesn't dust)
Intruder - Esword, stealth implant
Brawler - Syndi hardsuit, Esword
Infiltrator - Chameleon uniform, emag, supressed stetchkin - 3+1 mags
Bomber - 2x X4, minibomb, nukie explosion implant
Medic - Medic beam gun, egun, medkit

Elite classes
Nukeop - Standard nukeop loadout - (25 TC uplink), stetchkin
Wizard - 5/10 spell points, wizard uniform, space adaptation
Abductor - Abductor armour, teleportation scroll, esword, space adaptation
?Nightmare?

Admins can change the respawn delay of the siege controller, what outfits are available for example you could add deathsquad (idk why), or remove a class. They can manually change the phase of operation, so the machine can function even outside of the siege gamemode.
This gamemode was inspired by the Dwarfs Vs Zombies gamemode for minecraft.

## Why It's Good For The Game

A big problem with SS13, like real life, is you're not allowed to play the game, you cant kill people, you cant build WMDs (powergaming), even if you chose to make gamer gear what do you use it against? Worse, job progression revolves around combat, but you are not allowed to attack other people if you aren't an antagonist, not even other antagonists (validhunting), even then you aren't allowed to attack whoever you want (murderboning). Put simply your potential is limited. Enormous amounts of content are locked behind this limitation. This gamemode aims to solve these issues. Further it will probably increase pop because who wouldn't want to play this amazing mode where these are not frowned upon, but optimal:
- Murderbone
- Power Game
- Valid Hunt

The progression of almost every class relies on combat. But whether this combat materializes is uncertain, you could say that's what the point of nukeops is, but nukeops doesn't have a large preparation stage and so is largely removed from standard gameplay. Other gamemodes like gangs and cult can be criticized for not following standard gameplay. Siege's preparation stage is essentially normal SS13 but without restrictions. Siege provides a reason and removes your restrictions to actually do your job as it is designed.
- Botany - deadly plants factory
- virology - literally a bio weapons lab
- robotics - literally a mecha factory
- Toxins - literally bomb making
- Xenobiology, nanites, genetics - combat buffs
- chemistry - grenades, combat drugs
- cargo - make money to buy cool stuff (only guns and armour)
- engineering - build shit but why? everything the station needs already exists - repair shit? 
- atmos - deadly gasses
- medical - heal people - who needs to be healed?

Every department has a purpose, most will be performing their usual duties but on steroids on top of defending the station
Security - Hunt antags, prevent sabotage, oversee the armament of the station
Cargo - Enhanced duties
Engineering - Secure power and fortify the station, repair combat damage
Medical - Upgrade medical/ move it to somewhere more defendable, heal combat casualties
Science - Enhanced duties
Service - Floaters

Command has an enormous role, they will likely be choosing the central location that will be defended, where the nuke will be moved to, their task is to coordinate their department's resources into an effective defense. I don't imagine everywhere could be defended at once.

## Changelog
:cl:
add: Siege gamemode
add: SyndPDA (admin/gamemode spawn) which can spawn teleporters, dispensers and turrets
add: Energycore (admin/gamemode spawn) which fully recharges energy weapons
add: 13 new outfits (admin/gamemode spawn)
/:cl:

### CODE REVIEW

**Comment by mudzbe** [comment]
I didnt expect a conflict I've barely changed existing files

**Comment by williamcll** [comment]
Looks like a great event mode.

**Comment by mudzbe** [comment]
why am i being harassed

**Comment by ilikesaying** [comment]
class selection boxes need to be smaller

**Comment by williamcll** [comment]
For the testmerge round, the problem was we had roundstart full nukies. And against a crew of 7 this was next to impossible to beat.

**Comment by mudzbe** [comment]
> For the testmerge round, the problem was we had roundstart full nukies. And against a crew of 7 this was next to impossible to beat.

There werent "roundstart full nukies" first off they only showed up like 40 mins into the round and there were only two when they showed up, second they had less gear than nukies - nukies have 30TC and misc stuff, they had ~15TC worth of gear and misc stuff. In fact the crew probably had better gear - more guns and more numbers. I barely saw any preparation in the 40 mins, I helped hand out guns but when I was running around I didn't even see meds in the fridge, which is the minimum of what the crew should be doing. It's not supposed to be against 7 people anyways.

**Comment by ilikesaying** [comment]
The nukie ship can spawn an infinite number of troops, I, as the first nukie, had broken into the nukie base via the C4 in the explosives prep room, and hauled all items of use into the ship. 

The crew having better gear meant jack since they had no means to defend against unseen explosives and the vacuum of space.

**Comment by mudzbe** [comment]
> The nukie ship can spawn an infinite number of troops, 

So what the crew isn't meant to win.

> The crew having better gear meant jack since they had no means to defend against unseen explosives and the vacuum of space.

They would have if they used the 40 minutes to prepare. There are plenty of department hardsuits, eva suits (most syndies have space suits) and you could easily equip everyone with armoured swat suits but no one chose to. There was 1/2 the recommended pop for the mode, on the first time it was played, it was never going to be fair for the crew.

**Pull request closed without merging**
