### PR TITLE
Syndicate Name Generation Reference 2

### PR DESCRIPTION
**Pull request by mudzbe**
## About The Pull Request

Adds prefixes "Volta", "Gravesend", "Luddite", "Tri-Tach" to Syndicate Name Generation.

## Changelog
:cl:
add: Added more prefixes for syndicate name generation
/:cl:

### CODE REVIEW

**Comment by mudzbe** [comment]
I'm waiting in anticipation for when it rolls "Luddite Industries"

**Comment by Singularity69** [comment]
I know luddite and tri-tach but wtf does volta and gravsend came from?

**Comment by mudzbe** [comment]
They are both planets from Brigador

**Comment by MCterra10** [comment]
based and based-pilled

**Review by MCterra10 — APPROVED** [review]

**Pull request merged**
