### PR TITLE
[MIRROR] Tgui stat panel

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/2771
--------------------

**Fix chat HARDER ports:**
 - https://github.com/tgstation/tgstation/pull/54030/files
 - https://github.com/tgstation/tgstation/pull/54517

## Important
client.verbs +=, client.verbs -= and client.verbs |= is now not allowed and will not function properly. Once this is merged, all PRs will be required to do client.add_verb()

## About The Pull Request

Adds in the beautiful TGUI stat panel.
Actually includes all of the verbs.

Completely depreciates statclick and /datum/verbs

## Why It's Good For The Game

It looks good.
MC no longer lags the server.

**NOTE: TABS WERE NOT SORTED ALPHABETICALLY IN THESE SCREENSHOTS (Added that afterwards)** (actually I haven't fixed that yet even 1 day later)  <-- I have now

Status:
image
image
image
image
(Not lagging the game or the server, and updating in real time)
image
image
image
image

## Todo:
 - [x] Make it so you can resize the stat panel.
 - [x] Clean up some ungodly stat code.
 - [x] Fix the single ticket manager issue

## Important things to note / Potential Issues:
This completely removes the stat panel, so if TG chat fails to load the only way to use the fix-chat verb (which barely ever fixes chat) is to type in the command line. I'll port something that adds a message to chat from TG to help with this, but for now we have a message instead.

## Changelog
:cl:
add: TGUI stat panel
del: Old stat panel
del: Depreciates /datum/verbs
del: Depreciates statclick
refactor: Refactored how verbs are added to things
refactor: Refactors stat code
fix: Ports fix fix chat from TG station
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
sigh, holding for the moment. I kinda want some fixes if it's as bad as francium says.

**Comment by TheFakeElon** [comment]
revert testmerge is active upstream yeah. Don't merge here

**Comment by MCterra10** [comment]
lint failing because of tgui, ignore

**Comment by MCterra10** [comment]
YOLOO!!11

**Pull request merged**
