### PR TITLE
Austation map - Re-positions plumbing and viro, adds missing stuff

### PR DESCRIPTION
**Pull request by MisterMecky**
## About The Pull Request

Re-positions plumbing and virology for a better looking map. also adds a chem fridge to plumbing. Rearranges viro a little.

Also adds stuff from metastation that was missing from austation.

- Chaplain altar
- Virus extrapolator inside viro's bio-security closet

allchanges

## Why It's Good For The Game

Looks nicer.

## Changelog
:cl:
tweak: re-positions plumbing lab and viro
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
Oh *shit* yes

**Review by MCterra10 — APPROVED** [review]

**Comment by MisterMecky** [comment]
Got some bits and pieces that need to be changed

**Comment by Ohagi-Chan** [comment]
I love this layout a lot.
The position of chem looks much more natural.

I do have one last criticism though, which is that the viro's work station is standing directly in the way of their door.
Would it be possible to swap the equipment on their left and right sides, so that they can work standing to the side of the door instead of in front of it?  This may involve moving the entire lab closer to the chapel, or an extension.

**Comment by MisterMecky** [comment]
> I do have one last criticism though, which is that the viro's work station is standing directly in the way of their door.
> Would it be possible to swap the equipment on their left and right sides, so that they can work standing to the side of the door instead of in front of it? This may involve moving the entire lab closer to the chapel, or an extension.

Hows this?
viro

**Comment by MisterMecky** [comment]
This should be good to go, I am unaware of any issues.

**Review by MCterra10 — APPROVED** [review]

**Pull request merged**
