### PR TITLE
Headpats now gives a mood buff

### PR DESCRIPTION
**Pull request by totallynotkatfood**
## About The Pull Request

title

## Why It's Good For The Game

hugs give buffs, so why not headpats

## Changelog
:cl:
tweak: headpats now gives a mood buff
/:cl:

### CODE REVIEW

**Comment by thelaughingbomb** [comment]
Hugs are still better than headpats, but i guess now you can stack the mood effects?

**Comment by totallynotkatfood** [comment]
It's the same mood bonus as hugs but also wears off in 2 mins

**Comment by totallynotkatfood** [comment]
I guess i can make it wear off faster for preventing stacks

**Comment by thelaughingbomb** [comment]
Hugs provide a mood bonus of 1, 3 and 5
1 is hug with no trait
3 is with friendly trait
5 is with friendly trait and good mood

**Comment by totallynotkatfood** [comment]
headpats are just 1 even with friendly trait

**Comment by amidoingitright** [comment]
Speedmerge with no survivore

**Comment by coolsurf6** [comment]
Any one that headpats will become valid.

**Comment by TheFakeElon** [comment]
smh

**Comment by TheFakeElon** [comment]
time to abuse my powers for my mood buff fetish

**Comment by thelaughingbomb** [comment]
smh, doris do be abusing his powers tho 😳

**Comment by totallynotkatfood** [comment]
:winrar:

**Comment by TheFakeElon** [comment]
😳

**Comment by thelaughingbomb** [comment]
😳

**Comment by amidoingitright** [comment]
wait why was this closed in the first place?

**Comment by coolsurf6** [comment]
😳

**Pull request merged**
