### PR TITLE
New Maints Room: Wikipedia Server Room

### PR DESCRIPTION
**Pull request by YakiAttaki**
## About The Pull Request
This adds a new maints room: the wikipedia server room. Mostly just a trap room that locks someone in and plays a sound for them.
the sound that plays is this: https://youtu.be/nOPIu7isD3s

## Why It's Good For The Game
funny maints traps

## Changelog
:cl:
add: Added a new maints room: the Wikipedia server room
soundadd: added a new sound: wikipedia.ogg
/:cl:

### CODE REVIEW

**Comment by YakiAttaki** [comment]
travis breaking isn't my fault the dumb cunt just broke himself

**Comment by TheFakeElon** [comment]
Make it ask you for a $5 donation when the trap is activated

**Review by TheFakeElon — CHANGES_REQUESTED** [review]
Make it ask you for a $5 donation when the trap is activated

**Comment by TheFakeElon** [comment]
On a more serious note, that’s an mp3 to an entire YouTube video and could get us cOpYstRiKed

**Comment by YakiAttaki** [comment]
> On a more serious note, that’s an mp3 to an entire YouTube video and could get us cOpYstRiKed

i really doubt we'd get into trouble for that considering its a meme thing, the only thing I could really see would be the music in the background but it's completely overshadowed by the speaking and is in itself distorted

**Comment by YakiAttaki** [comment]
@TheFakeElon if you'd like, i can change it to https://www.youtube.com/watch?v=O4UeUfNPKAk&t=10s, but that ones got like surround sound and is very weird

**Comment by YakiAttaki** [comment]
https://youtu.be/4osqNpb6apQ or this one

**Pull request closed without merging**
