### PR TITLE
Prevents Cut Cable From Being Magically Red

### PR DESCRIPTION
**Pull request by park66665**
## About The Pull Request

Whilst red indeed is a beautiful color, we certainly don't want cables to turn red for no reason when cut. This PR prevents it by changing the order where the cables are initialized, so it correctly colors the stored cable piece.

I will upstream this if maintainers request it.

## Why It's Good For The Game

Better Immersion.

## Changelog
:cl:
fix: Cables now always return correctly colored cable pieces when cut
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
cable o x i d a t i o n

**Comment by park66665** [comment]
Technically, it ~~oxidates~~ turns red when the cable is half-layed (i.e. incomplete cables with a weird circular node) and then cut; stored cable color is properly updated when the cable is updated, e.g. when the cable gets completed.

**Comment by TheFakeElon** [comment]
Could you comment out the removed code instead, makes conflicts easier to track

**Comment by TheFakeElon** [comment]
And moving the “//austation — end” to the right spot

**Review by TheFakeElon — APPROVED** [review]

**Comment by park66665** [comment]
Maybe... maybe I can modularize this fix *somehow*?

**Pull request merged**
