### PR TITLE
Nitryl & Stimulum Buff

### PR DESCRIPTION
**Pull request by MrLostman**
_commissioned by Ohagi_
## About The Pull Request
**Nitryl below 20kPa**
user ignores encumbrance
user ignores damage slowdown
**Above 20kPa**
all of the above
kPa/4 burn damage
same old nitryl speed bonus

Stimulum has its speed buff back & ignores encumbrance

## Why It's Good For The Game
Atmo has one of the hardest leanring curves in the game while having some of the worst incentives. This pull request is to bring the job progression up to the level of other jobs. This will actaully encourage people to actually use the gases. Have you ever seen anyone make nitryl or stim?

Purging chems disable the buffs so it's not as powerful as it seems on the outset.

The progression of these gasses is not out of line to the power progression of other jobs and it has counter play.

## Changelog
:cl:
balance: buffed Nitryl & Stimulum 
/:cl:

### CODE REVIEW

**Comment by Mick1299** [comment]
You added your custom check breath to austation/code/modules/mob/carbon/life.dm, but the base check breath is under austation/code/modules/mob/living/carbon/life.dm. 

Not sure if this would have a negative impact

**Comment by MrLostman** [comment]
Nice catch I'll clean that up.

**Comment by Mick1299** [comment]
All minor errors fixed, Looks like a solid minor buff for a gas that is pretty time consuming to produce

**Comment by MrLostman** [comment]
Yeah, easy I don't really know how strict you want modularization to be I can rework this.

**Comment by MrLostman** [comment]
Need to repush this. Please close this PR

**Pull request closed without merging**
