### PR TITLE
Adds glass floors to science, arrivals and escape

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

see title

## Why It's Good For The Game

Glass floors isn't being used much

## Changelog
:cl:
add: Added glass floors to austation
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
screenshots pls

**Comment by jupyterkat** [comment]
see: map diff renders

**Comment by TheFakeElon** [comment]
Not sure how I feel about this, it looks a bit jarring in contrast with the rest of the station. Mostly because of the under-tile objects.

@MCterra10 What do you think?

**Comment by Mick1299** [comment]
If you like the glass floors, I can add them to arrivals, departures, and around the main hallway. Just need to move wires, pipes, and disposal pipes around so you get a clean view to space.

**Comment by MCterra10** [comment]
I don't really like this, seeing the pipes and shit through the glass is kinda weird. it doesn't blend well.

**Comment by jupyterkat** [comment]
I can make the pipes disappear but that kinda defeats the point of glass floors

**Pull request closed without merging**
