### PR TITLE
Sprite Revert Hardsuits : AKA Bee Spriters Suck

### PR DESCRIPTION
**Pull request by MrLostman**
Bee Sprites
image
Old Sprites
image

## Changelog
:cl:
imageadd: added old hardsuit and spacesuit sprites
/:cl:

### CODE REVIEW

**Comment by Ohagi-Chan** [comment]
G

**Comment by lordScrubling** [comment]
you swapped hos and sec in the screenshot just saying

**Comment by MrLostman** [comment]
bee

**Comment by MCterra10** [comment]
all these reverts are fine, except sec hardsuits which I personally kinda like

**Comment by amidoingitright** [comment]
the inhand sprites for the new sprites are ugly, always have been and always will be

**Comment by MCterra10** [comment]
waiting on either the reverts to sec hardsuits to be removed, or for lostmeme to resprite them

**Pull request closed without merging**
