### PR TITLE
[MIRROR] Move the race paywall stuff to config

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/2580
--------------------
## About The Pull Request

As per @ francinum 's request, I've moved the race paywall stuff to config to make it easier on downstream that use the module method.

[issue link stripped]

## Why It's Good For The Game

Config good hardcoded bad

## Changelog
:cl:
add: Added race paywall to config
config: Felinids are no longer paywalled.
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
we’d need to merge the other paywall PR for this to work.

**Comment by TheFakeElon** [comment]
Both of which I think is dumb

**Comment by MCterra10** [comment]
remirror

**Comment by MCterra10** [comment]
remirror

**Pull request merged**
