### PR TITLE
[MIRROR] The Great Resprite: Atomized Edition (Tools volume)

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/2487
--------------------
## About The Pull Request

Second part of the PR, wich i atomized for mantainer's sake.
the whole set can be seen here: #2339 
This one's toolset and belt,

## Why It's Good For The Game

Unique visuals, color marked equipment as tools and a facelift of some old sprites like toolbelts and inducers, Unified pallete and design if the entire set passes.

I swear this is the only thing that uses so much yellow.

image
image
image
image

## Changelog
:cl:
add: Engineering tools and toolbelts got a complete redesign.
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
alright this is nice, the main complaint with the stock part overhaul was art detail compatibility

**Comment by TheFakeElon** [comment]
BUT, I’m personally not 100% on some of these sprites, we could test merge to see how the playerbase feels

**Comment by TheFakeElon** [comment]
PR image isn’t up to date, you can see the updated changes in the upstream PR

**Comment by MCterra10** [comment]
we're merging regardless because fuck icon file conflicts

**Pull request merged**
