### PR TITLE
Updated Laserpointer to be more realistic

### PR DESCRIPTION
**Pull request by ZombiesVsPlants**
## About The Pull Request

Changed var/effectchance = 33 to var/effectchance = 5

## Why It's Good For The Game

I did this because laserpointers are way to OP

## Changelog
:cl:

balance:
Major reduction in chance for the laser pointer to have an effect per firing

/:cl:

### CODE REVIEW

**Comment by ZombiesVsPlants** [comment]
Wow zombies, you are so cool and smart and I agree with you fully

**Comment by ZombiesVsPlants** [comment]
wait this is my actual austation
fuck

**Comment by YakiAttaki** [comment]
changelog unclear, i ate the laser

**Comment by mudzbe** [comment]
Where did Robs hurt you?

**Comment by YakiAttaki** [comment]
The eyes, obviously

**Comment by ZombiesVsPlants** [comment]
Whoops missclick

**Comment by coolsurf6** [comment]
Bruh.

**Pull request closed without merging**
