### PR TITLE
Removes Botany Hand Holding

### PR DESCRIPTION
**Pull request by MrLostman**
## About The Pull Request
Removes botany chem dispenser, botany has ghetto alternatives as well as just getting it from chem or getting engineering to build them one.

## Changelog
:cl:
del: removes botany chem dispenser
/:cl:

### CODE REVIEW

**Comment by Mick1299** [comment]
Would you consider adding the board into tech storage?

**Comment by TheFakeElon** [comment]
All this does is make botanists break into tech storage again roundstart (see above). I agree that departments shouldn't have everything they need to operate at max efficiency roundstart, but without mutagen botany is barely playable if you intend to do anything except help chef.

If you want to remove the dispenser, there needs to be an alternative with *similar* functionality, whether it's easily accessible mutagen plants or something else entirely. What botany has now is not ideal but it's so much better than what it was before

**Comment by TheFakeElon** [comment]
(also your current implementation will just lead to botanists voting for metastation instead of austation, for what it's worth)

**Comment by MrLostman** [comment]
botany can make its own mutagen this is literal hand holding

**Comment by BusterTornado** [comment]
Yay, now I can get instant-killed by botany plants 85 minutes into the game instead of 70 minutes. Thanks Lostman!

**Comment by PortableSeedExtractor** [comment]
merge this c*oders

**Comment by MCterra10** [comment]
yeah sorry lostmeme, I'm closing this one. As elon said, competent botanists will now just steal the chem dispenser board from tech storage again at roundstart, adding 5 minutes to their routine, and new botanists will be forced to beg chemistry for mutagen again, and be ignored. This would be more at home on bee which is an MRP server, not on austation.

**Pull request closed without merging**
