### PR TITLE
Morphine Rework

### PR DESCRIPTION
**Pull request by MrLostman**
## About The Pull Request
Morphine is no longer a sedative and now gives no damage slow.

## Why It's Good For The Game
Currently we have tones of sedatives and really only one type of buff chem. This takes morphine a rather useless chem outside of killing people in sleepers and gives it an actual use.

## Changelog
:cl:
tweak: sedative effect of morphine removed, nodamageslow added
/:cl:

### CODE REVIEW

**Review by MCterra10 — CHANGES_REQUESTED** [review]
I'm not too happy with how much of a massive buff chem this makes morphine. No damage slowdown is a HUGE combat advantage. I think there needs to be some sort of associated downside given how common it is.

Also this lets you use full hardsuits effectively in combat because it negates their slowdown too lol

**Comment by DrDuckedGoose** [comment]
Nej

**Comment by lordScrubling** [comment]
doesnt it already make you ignore damage slowdown while making you sleepy
pr doesnt even delete anything
does morphine not already exist on austation

**Comment by MrLostman** [comment]
@lordScrubling AuStation coding is mostly done modulary. This code overwrites the underlying bee code.

**Comment by MCterra10** [comment]
Seeing the changes, I just feel this makes morphine too powerful in its current form. I'm going to close this.

**Pull request closed without merging**
