### PR TITLE
Spriting Revert Misc : AKA mostly engineering shit

### PR DESCRIPTION
**Pull request by MrLostman**
Reverts engineering, ce and atmo jumpsuit. 
Reverts backpacks, engineering satchel and dufflebag.
Reverts hardhats.
Reverts engineering boots

## Changelog
:cl:
imageadd: added old hardsuit and spacesuit sprites
/:cl:

### CODE REVIEW

**Comment by lordScrubling** [comment]
firesuits?

**Review by TheFakeElon — APPROVED** [review]

**Comment by TheFakeElon** [comment]
Code approval. Pretty torn on the actual change

**Comment by MCterra10** [comment]
checking current sprites one sec. some of this I like, some I don't

**Comment by MCterra10** [comment]
This is fine, especially magboots which I hate.

**Pull request merged**
