### PR TITLE
Maid dress as a metacoin purchasable roundstart item

### PR DESCRIPTION
**Pull request by jbox144**
## About The Pull Request

Allows the maid dress and maid costume to be bought from the AuCoin (Metacoin) store. The maid dress is available for 2,500 but is restricted to janitors. The maid costume is available for a mere 10,000 coins and your own dignity.

## Why It's Good For The Game

I... don't actually know.

## Changelog
:cl:
add: Added the maid dress and maid costume as an item purchasable from the AuCoin store.
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
N

**Comment by amidoingitright** [comment]
We need this

**Comment by amidoingitright** [comment]
But remove it's class restriction from janitors

**Comment by MCterra10** [comment]
Why tho?

**Comment by amidoingitright** [comment]
Making it Aucoin buyable would be nicer because then I wouldn't have to break into theatre or buy a resupply crate from cargo
Plus the maid costume looks nice

**Pull request closed without merging**
