### PR TITLE
Adds Australium items

### PR DESCRIPTION
**Pull request by totallynotkatfood**
## About The Pull Request

splash a beaker of australium on your item of choice to get it

## Why It's Good For The Game

we have australium, why not.

## Changelog
:cl:
add: Added australium items
/:cl:

### CODE REVIEW

**Comment by YakiAttaki** [comment]
make it so you have to pay $1.49 to get a chance to get an Australium weapon

**Comment by Mick1299** [comment]
Any plans to make this effect stats? Or is it literally just a skin?

**Comment by totallynotkatfood** [comment]
you can add the effects

**Comment by ZombiesVsPlants** [comment]
can you consume the australium food?

**Comment by totallynotkatfood** [comment]
you can and i’ll add the australium reagent in them soon

**Comment by MCterra10** [comment]
absolutely based and redpilled, time to pimp out my captain's sabre

**Pull request merged**
