### PR TITLE
[MIRROR] Fixes music text input length

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/2632
--------------------

## About The Pull Request

This sets the input to the maxlines*maxlinechars
[issue link stripped]

## Why It's Good For The Game

People can paste music again

## Changelog
:cl:
fix: You can now paste longer songs again.
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
remirror

**Comment by TheFakeElon** [comment]
remirror

**Comment by TheFakeElon** [comment]
remirror

**Comment by MCterra10** [comment]
remirror

**Pull request merged**
