### PR TITLE
[MIRROR] another random maint expansion: making maint a tad more dangerous

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/2273
--------------------
## About The Pull Request
- adds 34 new random maint rooms, credit to GizkaFreechman for most. 
- new gimmick job, the VIP. the VIP is rich.
- adds random maint traps: invisible traps that may or may not spawn. they range from breaking all the lights in a room to spawning mobs nearby
- also removes knockdown from faithless while i was in his files cuz i forgot it awhile ago

## Why It's Good For The Game
I hate you all, and i want to remind you that no one is fucking safe

## Changelog
:cl: Zeskorion, GizkaFreechman, thatguythere03
add: 28 random maint rooms by GizkaFreechman, edited by myself
add: Random maint traps
add: cluwne rune, which can be used by cultists in a manner similar to an invocation rune, if the Honkmother has blessed one of the invokers with her presence
add: new random maint job, the VIP. he's rich, apparently important, and actually probably quite useless.
imageadd: sprites for new job and cluwne rune by thatguythere03
tweak: edited most random maint maps to make maint easier to get through (changing table placements and such)
balance: faithless no longer has a 12% chance to stun for 6 seconds on hit
/:cl:

### CODE REVIEW

**Comment by thelaughingbomb** [comment]
oh finally, its about time

**Comment by MCterra10** [comment]
I want static maint back so bad

**Comment by PowerfulBacon** [comment]
Problems upstream

**Comment by MCterra10** [comment]
I always stall these maint PRs as long as I can

**Comment by PowerfulBacon** [comment]
After a quick test on local, it definitely works. Must have been a merging issue or something to do with testmerges. I am going to give it another shot upstream and see how it goes

**Comment by DungeonPenguin** [comment]
cool and good

**Comment by PowerfulBacon** [comment]
After testing again, it seemed to be fine

**Pull request merged**
