### PR TITLE
Add a pool to randomized maints

### PR DESCRIPTION
**Pull request by totallynotkatfood**
## About The Pull Request

maint pools

## Why It's Good For The Game

maint pools

## Changelog
:cl:
add: Added pools to random maints
/:cl:

### CODE REVIEW

**Comment by YakiAttaki** [comment]
dirty disgusting unfiltered maint pools

**Comment by YakiAttaki** [comment]
someone's going to fill it with sarin

**Comment by TheFakeElon** [comment]
that someone is based

**Comment by YakiAttaki** [comment]
@totallynotkatfood what's the maints pool look like?

**Comment by totallynotkatfood** [comment]
check the map diff renders

**Comment by YakiAttaki** [comment]
oh cool it's got a controller

**Pull request merged**
