### PR TITLE
nerfs 3 fucking pixels sound bit

### PR DESCRIPTION
**Pull request by thelaughingbomb**
## About The Pull Request

The "3fuckingpixels" sound bit on round end is too loud.

## Why It's Good For The Game

Loud bad.

## Changelog
:cl:
balance: Nerfs 3 fucking pixels
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
lol

**Comment by coolsurf6** [comment]
lol

**Comment by coolsurf6** [comment]
Bruh just, turn down your volume 🤔

**Comment by thelaughingbomb** [comment]
bruh i have my volume set to 20%

**Pull request merged**
