### PR TITLE
[MIRROR] UUID generation / Discord verification

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/2163
--------------------
Adds the relevant DM code for discord verification. Generates a SHA256 uuid when needed and stores it in the DB.

### CODE REVIEW

**Comment by coolsurf6** [comment]
SQL changes, spicy

**Comment by MCterra10** [comment]
pending travis and SQL updates

**Comment by Crossedfall** [comment]
Ike's description says it's for Discord verification, but it can be used to verify accounts for pretty much any service. We'll be using it for Discord and our Forums. The topic call makes all that pretty easy.

**Comment by MCterra10** [comment]
database updated

**Pull request merged**
