### PR TITLE
A few minor mapping changes to Austation

### PR DESCRIPTION
**Pull request by Mick1299**
## About The Pull Request
Makes a handful of minor mapping changes
- Adds a light to starboard aft solars, and the atrium outside the gravity generator
image
image

- fixes a manifold in the incinerator spawning under the tile
image

- adds a camera to the service lathe room
image

- moves some lights and adds a camera to the science shuttle dock
image

- Finally, and probably most controversially, redefines the perma toilet area to be in port bow maints, shielding it from radiation storms.
image

## Why It's Good For The Game
a bunch of minor quality of life updates for players

## Changelog
:cl:
add: A few lights, cameras to service lathe and science shuttle dock
add: radiation shielding to the perma toilet
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
good changes and perma QoL imo :+1:

**Review by MCterra10 — APPROVED** [review]

**Comment by mudzbe** [comment]
Did you end up keeping the zoning for the toilet door, it doesn’t look like it, unless the picture is out of date. Are you sure the science shuttle dock camera reaches all the way to the bottom tile? It looks a bit far

**Comment by Mick1299** [comment]
I've changed it locally, just haven't pushed it to my branch yet. 

The camera covers every tile except one of the bottom corners. That's intentional, as I'm not a huge fan of AIs having 100% perfect sight in all rooms.

**Comment by Mick1299** [comment]
My Git and Local files are having an aneurism over this. Closing until I can fix some things my end

**Pull request closed without merging**
