### PR TITLE
Finishes coilguns

### PR DESCRIPTION
**Pull request by TheFakeElon**
(mostly)
## About The Pull Request

Fixes a few coilgun bugs
Made a better sound (edited an old sound I made) for CG super chargers

Adds a coilgun pipe dispenser, it's like the normal pipe dispensers in atmos but requires materials to work. It resides in secure storage roundstart on austation, subject to change depending on how hard it gets abused

## Why It's Good For The Game

Original coilgun PR wasn't completely finished and could only be spawned by admins

## Changelog
:cl:
add: Added the coilgun fabricator!
add: Added the coilgun fabricator to secure engi storage.
add: Added a random maint room containing the coilgun fabricator
fix: fixes a few coilgun bugs
code: misc coilgun performance optimizations
soundadd: adds a new discharge sound for coilgun super charges
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
:clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap:

**Comment by Ohagi-Chan** [comment]
that'll be the day

**Comment by MCterra10** [comment]
not testmerged, as it seems to have a conflict with some other testmerge PR

**Comment by MCterra10** [comment]
Also json syntax error in the linters

**Review by MCterra10 — CHANGES_REQUESTED** [review]
Please add
```json
{}
```
to bouncy.json to squelch the linter error

**Comment by TheFakeElon** [comment]
I'll re-open when it's ready :)

**Comment by MCterra10** [comment]
(he didn't finish coilguns)

**Pull request closed without merging**
