### PR TITLE
Autism fort Lava ruin and ghostrole

### PR DESCRIPTION
**Pull request by Ohagi-Chan**
## About The Pull Request
Adds the new autist ghost role who was so preoccupied with their own nonsense that they missed the shuttle - now they continue to be a reclusive nerd on lavaland.
Their lab is outfitted with tools for mad science and body modification, such as virology, surgery, xenobiology and more.
They are neutral to other factions, not necessarily friends nor enemies to other players, and have turrets to defend themselves with against would-be annoyances.

## Why It's Good For The Game
New content, the Autist is somewhere between a learning ground and a practical exercise in defense.  Steal or destroy their work, or try to work together with them to achieve autistic powergaming.  2 spawns allows for some cooperation as a sort of mini-faction.

## Changelog
:cl:
add: lavaland_biodome_autism map
add: autist ghostrole
fix: tweaked a bad scrubber pipe in the pet hospital map
/:cl:

New map
autism biodome

Adjusted scrubber pipe (no longer a manifold bridging the scrubbers and distro together).
Annotation 2020-08-31 201013

### CODE REVIEW

**Comment by TheFakeElon** [comment]
beestation DME include changes, also give screenshots

**Comment by TheFakeElon** [comment]
There needs to be flavour text explaining that they can't leave their base too.

**Comment by TheFakeElon** [comment]
your austation includes are messed up too

**Comment by Ohagi-Chan** [comment]
> fix beestation DME include changes, also give screenshots

I don't intend to change that.  The Beestation.dme change is because shadowtongue is ordered badly and this affects literally every coders' experience with the file, the compiler always tries to fix the order, which is not actually a bad thing.



> There needs to be flavour text explaining that they can't leave their base too.

I never intended to prevent them from leaving the base.  Some of their work can't be performed without leaving to gather materials from lavaland.



> your austation includes are messed up as well

What exactly is wrong with my austation/includes.dm?
I added 3 new files to the austation directories, there are 3 new lines in that file.  I see no problem.

**Comment by thelaughingbomb** [comment]
What if this ruin had the unobtainable auto surgeon?

**Comment by Ohagi-Chan** [comment]
> What if this ruin had the unobtainable auto surgeon?

I can easily add that, but should I?
the autists should be capable of performing surgery normally, with either 2 spawns, or a slime clone.
If I add something like that then it really is just loot for miners to steal - in contrast to the rest of the setup which is fairly useless unless you put time into it.

**Comment by totallynotkatfood** [comment]
no, someone will just break in and yoink it

**Comment by coolsurf6** [comment]
Pog

**Comment by MCterra10** [comment]
please tell me why this ruin exists purely for people to get gamer gear

**Comment by MCterra10** [comment]
like, not even kidding, that is *literally* its purpose

**Comment by Ohagi-Chan** [comment]
The gamer gear isn't really any good unless you invest 30 minutes in it.
None of the work is done for people who spawn here or happen across it, the xenobiology room doesn't even have a console for doing xenobio properly.  Free golems and Ashies honestly have much better loot than this ruin; illegal tech, omnilathe, RCD to name a few.  This ruin has slimes, something golems can get set up almost just as easily, and ATVs, cool but not actually useful - they're actually slower than running and hinder your pickaxe use.  I can remove the laser turret parts if you want, I've been told that laswer guns are innefective against fauna anyway.

The purpose of this ghostruin is to give people an opportunity to mess about with this combination of systems all in one place rather than how you might otherwise discover them, in distant corners of maint, if at all.

**Comment by MCterra10** [comment]
Then can you put *superhot* lava around it like with the syndie base, so you can't just respawn, get gamer shit and walk back to the station with your infinite breath mask, aheals and clone bodies?

**Comment by MCterra10** [comment]
The superhot lava, btw is a subtype of lava that can't be RCDd

**Comment by Ohagi-Chan** [comment]
Closing.
If you don't like the idea then you don't like it.  I gave up on it being merged 3 days ago when you applied the stinky tag.  I'm upset that I spent time making this, but beating around the bush compromising and arguing for a few days isn't going to make me feel better either.

**Pull request closed without merging**
