### PR TITLE
Observers don't need to be told about the correct way to load the makeshift pistol

### PR DESCRIPTION
**Pull request by thelaughingbomb**
## About The Pull Request

Changes a line so observers don't get the notice that you cant load the makeshift pistol by the box. Also makes it so observers dont see the message about jamming.
## Why It's Good For The Game
Observers dont need to know this

## Changelog
:cl:
fix: Observers are no longer being told about loading ammo boxes into makeshift pistol, or that it jams.
/:cl:

### CODE REVIEW

**Comment by thelaughingbomb** [comment]
latest commit to resolve line ending conflict

**Comment by MCterra10** [comment]
bro this changes literally nothing except the lineend lmao

**Comment by MCterra10** [comment]
check changed files

**Comment by thelaughingbomb** [comment]
ah fuck lmao

**Comment by thelaughingbomb** [comment]
there we go

**Pull request merged**
