### PR TITLE
[MIRROR] [PORT] Replaces travis with github-actions

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/2902
--------------------

## About The Pull Request

ports
tgstation/tgstation#54668
tgstation/tgstation#54833
tgstation/tgstation#54780
tgstation/tgstation#54805
tgstation/tgstation#53669
tgstation/tgstation#52529

## Why It's Good For The Game

Github-actions is faster and more consistent

### CODE REVIEW

**Comment by TheFakeElon** [comment]
remirror

**Comment by jupyterkat** [comment]
pog

**Comment by MCterra10** [comment]
Maybe another time. Travis works fine

**Comment by TheFakeElon** [comment]
remirror

**Pull request closed without merging**
