### PR TITLE
"0g can be safely ignored" - Terra, 26/09/2020

### PR DESCRIPTION
**Pull request by jbox144**
## About The Pull Request

image

SO

I said to terra to unmerge licking or I'd port this. They didn't unmerge licking. So I'm fucking porting

YOU DID THIS TERRA. YOU DID THIS TO YOURSELF. **YOU ONLY HAVE YOURSELF TO BLAME HERE**

Someone get me a good therapist or some rope and a chair.

image

## Why It's Good For The Game

If it threatens Terra to unmerge licking, its good.

## Changelog
:cl:
del: Compilatron's sanity
/:cl:

### CODE REVIEW

**Comment by thelaughingbomb** [comment]
what the fuck

**Comment by amidoingitright** [comment]
the end of austation

**Comment by MCterra10** [comment]
Ok this is cool but can you add it to a tech node like Biological Processing so we can get them?

**Comment by jbox144** [comment]
> 
> 
> what the fuck

kill me

**Comment by jbox144** [comment]
> 
> 
> Ok this is cool but can you add it to a tech node like Biological Processing so we can get them?

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by jupyterkat** [comment]
:winrar:

**Comment by amidoingitright** [comment]
it all RETURNS TO NOTHING, IT JUST KEEPS TUMBLING DOWN TUMBLING DOWN TUMBLING DOOOWN

**Comment by MCterra10** [comment]
AND IF YOU CLOSE YOUR EYES
DOES IT ALMOST FEEL LIKE 
NOTHING CHANGED AT ALLL

**Comment by jbox144** [comment]
> Ok this is cool but can you add it to a tech node like Biological Processing so we can get them?

here's a crafting recipe. aaaaaaaaaaaaa

**Comment by amidoingitright** [comment]
ahaahahahahahaha

**Comment by TheFakeElon** [comment]
Cringe

**Comment by TheFakeElon** [comment]
Lick PR was funny but now you’ve killed the joke 😔

**Comment by amidoingitright** [comment]
shame /s

**Pull request closed without merging**
