### PR TITLE
CTRL+click jumpsuits to cycle sensors.

### PR DESCRIPTION
**Pull request by jbox144**
## About The Pull Request

Ever had those times when you wanted to change your sensors... but didn't want to open up that *ancient* context menu? Well, that is a problem no more! You can now CTRL+click your jumpsuits to cycle through their settings, no context menu needed!

## Why It's Good For The Game

It's a slightly better way to toggle suit sensors than using a context menu.

## Changelog
:cl:
add: You can now CTRL+click jumpsuits to cycle their sensor settings.
/:cl:

### CODE REVIEW

**Review by MCterra10 — COMMENTED** [review]
maybe a description hint to tell you this is a thing?

**Comment by TheFakeElon** [comment]
What's wrong with alt clicking

**Comment by jbox144** [comment]
> What's wrong with alt clicking
> 
> edit: nevermind 😅

mmm yes

**Review by MCterra10 — CHANGES_REQUESTED** [review]
add a description hint that this exists

**Comment by jbox144** [comment]
> 
> 
> add a description hint that this exists

done, sorry

**Review by MCterra10 — APPROVED** [review]

**Pull request merged**
