### PR TITLE
Adds felinid language

### PR DESCRIPTION
**Pull request by Ohagi-Chan**
## About The Pull Request
Adds a new language for felinids to annoy the crew with,
it has a total of 4 syllables until Melvyn gives me a larger list, so expect it to sound repetitive.
Felinid's tongues are also the most sensitive tongues on the planet now, whatever that means.

## Why It's Good For The Game
Melvyn wants this.

## Changelog
:cl:
add: adds cat tongues
add: adds meownese
tweak: felinids now have cat tongues
/:cl:

### CODE REVIEW

**Comment by Ohagi-Chan** [comment]
In my opinion, the icon is too pale at the moment.

**Comment by Ohagi-Chan** [comment]
Hmmm.
Melvyn did warn me not to use the same filename for dmis.
I will fix this tomorrow.

**Comment by TheFakeElon** [comment]
no

**Comment by park66665** [comment]
Guess I will then quite often be spammed with "the strong flavor of [whatever flavor]" my catgirl character eats something. 😄

**Comment by amidoingitright** [comment]
Aww come on I must have done that wrong before because I swear I made a cat tongue organ

**Comment by TheFakeElon** [comment]
Cursed tongue description. Cat girls aren’t actually cats lol

**Comment by Ohagi-Chan** [comment]
> Aww come on I must have done that wrong before because I swear I made a cat tongue organ

I got the same issue as you during my earlier tests.
What you did wrong is most likely you forgot to give human tongues the ability to speak the language, (provided the mob has learnt it.)

**Comment by Ohagi-Chan** [comment]
also, @amidoingitright Give me more content dammnit!
I've got the PR working, but I'm not inventing your content for you.
"Meownese" is a placeholder, I hope you realise.

**Comment by park66665** [comment]
Tg chose the name "nekomimetic"; hope it helps you:
tgstation/tgstation#52958

**Comment by TheFakeElon** [comment]
> Melvyn did warn me not to use the same filename for dmis.

Don’t, there’s no point. Every other austation icon file uses a normal name. Keep it the same for consistency’s sake

**Comment by amidoingitright** [comment]
https://github.com/austation/austation/pull/2063/files use that as content

**Comment by MCterra10** [comment]
didn't this get removed already?

**Comment by Ohagi-Chan** [comment]
> didn't this get removed already?

Melvyn didn't get it working when he tried to do this.
This pr is my attempt that actually works.

**Comment by MCterra10** [comment]
Nah, it did work and we had it testmerged for a while before it was removed

**Comment by TheFakeElon** [comment]
Oh it did? I thought felinids weren't starting with the language

**Comment by Ohagi-Chan** [comment]
I've been talking to Terra in DMs.
Looks kinda like melvyn got his pr denied so he wanted to try getting someone else to add the feature.

I'm annoyed to have another red label but honestly I have no real investment in getting this feature into the game.

**Comment by TheFakeElon** [comment]
@Ohagi-Chan Getting someone else to PR a feature that was recently closed will not make it any more likely to be merged. Also, if you're worried about getting closed just ask a maintainer before PRing

**Pull request closed without merging**
