### PR TITLE
ports bluespace jars

### PR DESCRIPTION
**Pull request by TheFakeElon**
## About The Pull Request

bluespace jars from citadel, basically a one use pokeball that requires illegal tech

## Why It's Good For The Game

Illegal tech doesn't really have any fun stuff besides nanites yet, this is a gimmicky yet useful tool for traitors, blood brothers and anyone with an imagination 

(doesn't work on megafauna, sorry robs)

## Changelog
:cl:
add: Bluespace jars
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
that was quick

**Comment by totallynotkatfood** [comment]
coom jar :winrar:

**Comment by Ohagi-Chan** [comment]
damn you, conflicting bastard.

**Comment by amidoingitright** [comment]
cant wait till i can force someone into the jar and fill it with milk

**Comment by zeskorion** [comment]
Bro why u portin cum jar from citadel you furry

**Comment by TheFakeElon** [comment]
sadly, it can't store reagents

**Comment by YakiAttaki** [comment]
the best use i can think for this is a ninja with protect

**Comment by TheFakeElon** [comment]
ow

**Comment by MCterra10** [comment]
I'll merge this, code is fully modular

**Pull request merged**
