### PR TITLE
[MIRROR] Wiremod port

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/4676
--------------------

## About The Pull Request

PRs ported so far:
https://github.com/tgstation/tgstation/pull/59348
https://github.com/tgstation/tgstation/pull/59459
https://github.com/tgstation/tgstation/pull/59584
https://github.com/tgstation/tgstation/pull/59592
https://github.com/tgstation/tgstation/pull/59613
https://github.com/tgstation/tgstation/pull/59345	
https://github.com/tgstation/tgstation/pull/58419 (only few parts)
https://github.com/tgstation/tgstation/pull/59728
https://github.com/tgstation/tgstation/pull/59724
https://github.com/tgstation/tgstation/pull/59743
https://github.com/tgstation/tgstation/pull/59850
https://github.com/tgstation/tgstation/pull/59635
https://github.com/tgstation/tgstation/pull/59866

map changes included 

This is dependent on #4623 and #4678

## Changelog
:cl: Watermelon914, Mothblocks
add: Wiremod, circuit replacement.
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
remirror

**Comment by MCterra10** [comment]
missing mirror

**Comment by MCterra10** [comment]
domirror 4678

**Comment by MCterra10** [comment]
dependencies resolved, updating PR

**Comment by MCterra10** [comment]
?remirror

**Comment by MCterra10** [comment]
remirror

**Comment by MCterra10** [comment]
?rebuild tgui

**Comment by MCterra10** [comment]
pending mapping updates if checks pass

**Pull request merged**
