### PR TITLE
Makes it so Freezers/Heaters can change layers through the maintenance panel

### PR DESCRIPTION
**Pull request by totallynotkatfood**
## About The Pull Request

Freezers/Heaters can now change layers by multitooling them when the maintenance panel is open

## Why It's Good For The Game

It's simply more convenient

## Changelog
:cl:
tweak: thermomachines can now change layers through maint panel
/:cl:

### CODE REVIEW

**Comment by thelaughingbomb** [comment]
You can change the layer by multitooling the circuit, but this is convenient.

**Comment by TheFakeElon** [comment]
I'd recommend using the tweak CL for this, not that it matters at all but "code" generally means cleaning up internal things.

**Comment by MCterra10** [comment]
conflict

**Comment by totallynotkatfood** [comment]
j u m p s k i r t s

**Pull request merged**
