### PR TITLE
goon bread except we do it differently it so that it's under AGPL

### PR DESCRIPTION
**Pull request by TheFakeElon**
## About The Pull Request

adds DISPOSAL TUBE BREAD! bread can be compressed into BETTER BREAD until shit starts breaking and everyone's day is ruined

## Why It's Good For The Game

chef buff chef buff! A nice autism project for cargo techs/engineers/chefs.

## Changelog
:cl:Terra, TheFakeElon
add: Disposal tube bread machine
add: Many new different bread types
add: deathchems exclusive to bread
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
Bad idea

**Comment by thelaughingbomb** [comment]
speed merge when

**Comment by MCterra10** [comment]
@zeskorion mad bro?

**Comment by TheFakeElon** [comment]
Progression rework soon(tm)

**Comment by ZombiesVsPlants** [comment]
removes loafer from cold room? noooooooo

**Comment by TheFakeElon** [comment]
roundstart access to **_the bread machine_** with no effort or searching required was kinda unfun

**Comment by MCterra10** [comment]
It's finally ready!

**Comment by coolsurf6** [comment]
Will there be a write up or a guide made about this bread? There were alot of changes and I am a bit behind on them all.

**Comment by totallynotkatfood** [comment]
not until peer sets up our wiki

**Comment by coolsurf6** [comment]
No bread guide, :(

**Pull request merged**
