### PR TITLE
Fix Paramedic Access

### PR DESCRIPTION
**Pull request by YakiAttaki**
## About The Pull Request
Paramedics on bee have severely reduced access. This fixes it.

## Why It's Good For The Game
Lets paramedics paramedic again.

## Changelog
:cl:
fix: Paramedics now have their full access back. Get in there and get the man out alive, EMT!
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
Tbh I think they don't have cloning access because it just makes them a better medical doctor

**Comment by YakiAttaki** [comment]
Tbh I don't think they have cloning access on tg because tg removed cloning

**Comment by MCterra10** [comment]
I'd have to check that one hold tight. I was pretty sure they never had it to begin with

**Comment by MCterra10** [comment]
hmm, I stand corrected. They did originally have cloning access:
Original access list:
```
access = list(ACCESS_MEDICAL, ACCESS_MORGUE, ACCESS_SURGERY, ACCESS_GENETICS, ACCESS_CLONING, ACCESS_MECH_MEDICAL, ACCESS_MINERAL_STOREROOM, ACCESS_MAINT_TUNNELS, ACCESS_EVA, ACCESS_ENGINE, ACCESS_CARGO, ACCESS_HYDROPONICS, ACCESS_RESEARCH)
minimal_access = list(ACCESS_MEDICAL, ACCESS_MORGUE, ACCESS_CLONING, ACCESS_MECH_MEDICAL, ACCESS_MINERAL_STOREROOM, ACCESS_MAINT_TUNNELS, ACCESS_EVA, ACCESS_ENGINE, ACCESS_CARGO, ACCESS_HYDROPONICS, ACCESS_RESEARCH)
```

**Comment by MarkSuckerberg** [comment]
god bless y'all for doin this, this is what I wanted for EMTs when I originally made em but ike asked me to turn down the access so they're how they are now. (also these aren't /tg/ parameds, they made em after we did)

**Comment by YakiAttaki** [comment]
it's not like they have access to anywhere restricted, idk why they'd ask you to turn the access down

**Pull request merged**
