### PR TITLE
Xenobiology crates

### PR DESCRIPTION
**Pull request by ZombiesVsPlants**
## About The Pull Request

Makes it so cargo can buy slime extracts for lots of money

## Why It's Good For The Game

The extracts allow you to do some cool things with slimes yet doesn't give you the power gaming of crossbreeds
also, sci has something to spend their budget on in order to get niche extracts if RNG is not in their favor

## Changelog
:cl:
add: adds Xenobiology crates to cargo
/:cl:

### CODE REVIEW

**Comment by ZombiesVsPlants** [comment]
ah fuck sakes let me fix it

**Comment by Ohagi-Chan** [comment]
so what about a cheaper, 4x grey core pack?

**Comment by ZombiesVsPlants** [comment]
yeah I'd be fine adding that

**Comment by ZombiesVsPlants** [comment]
alright I gotta fix these bugs later, closing

**Comment by coolsurf6** [comment]
Spicy

**Comment by ZombiesVsPlants** [comment]
just gonna open so I can see Travis's report

**Comment by ZombiesVsPlants** [comment]
I have no idea what is wrong with the code :(

**Comment by ZombiesVsPlants** [comment]
I think it's literally just travis
The command "tools/travis/check_grep.sh" exited with 1.
is the only red thing and it has been happening on all the other recent PR's

**Comment by thelaughingbomb** [comment]
The error isnt related to you

**Comment by ZombiesVsPlants** [comment]
niiiiiiice

**Comment by TheFakeElon** [comment]
Yeah, Travis is fucked atm.

**Comment by TheFakeElon** [comment]
What’s the point of making the grey crate illegal? Shouldn’t that be a red/oil only crate thing (although I don’t think any of them should be)

**Comment by TheFakeElon** [comment]
Also, this lets traitors completely cheese the steal extract objective.

**Comment by ZombiesVsPlants** [comment]
an oil illegal crate is a good idea, but you are right about the steal objective cheese, any suggestions or should I scrap this?

**Comment by TheFakeElon** [comment]
I mean, the easiest way would be making bought extracts a child of normal extracts and exclude said child from the objective. But it’d probably be better to do it with obj flags if you can. :)

**Comment by Mick1299** [comment]
Steal extract is already one of the easiest objectives, I doubt its worth the effort of coding a subset just to cuck traitors.

**Comment by TheFakeElon** [comment]
> Steal extract is already one of the easiest objectives, I doubt its worth the effort of coding a subset just to cuck traitors.

An objective shouldn’t be made easier because it’s already easy

**Comment by ZombiesVsPlants** [comment]
making it so cargo extracts can't be used for the steal objective could be confusing especially for new players. Especially if science uses it for its intended purpose (buying to bypass time/rng) and a traitor picks it off their dead bodies yet still gets a redtext simply because it was bought from cargo and not made in sci.

**Comment by ZombiesVsPlants** [comment]
Also if I were to try and circumvent that by adding a description to the steal extract objective that it had to be from science, that would involve me making an austation note and making this PR non-modular

Plus, the crates cost a ton and you still need toxin access (or other ways to break it open) in order to get to the cores
I feel like for an easy objective, going through that work while not being caught is fair

The other way to get an extract of course is through the illegal crate but I'm changing it to be expensive and hold oil/red extracts

**Comment by coolsurf6** [comment]
Why not change it so you have to have a crossbreed extract instead of a normal extract?

**Comment by ZombiesVsPlants** [comment]
stealing an extract is meant to be easy and the time investment required to gather at least 10 cores, grow a baby to an adult, and then feed it, all without access to that area (probably) is a little troublesome and would make it a far harder objective.

Maybe a good thing to add as a medium objective though!

**Comment by Ohagi-Chan** [comment]
Stealing a minimum of 6000 credits, to be able to buy these crates with only 8 cores, is a fair enough challenge for a traitor who wants to go that route.

**Comment by TheFakeElon** [comment]
> Stealing a minimum of 6000 credits, to be able to buy these crates with only 8 cores, is a fair enough challenge for a traitor who wants to go that route.
> 
> Inb4 "cargo traitor".
> Cargo doesn't start with enough cash that you'll get off scott free for wasting 6000c in the early game. You'll still need to work for it - or you could just steal some from sci, which sounds a lot easier.

can literally just ask cargo or request it on the console. much less likely to get shit

**Comment by ZombiesVsPlants** [comment]
You can also buy a reflection vest from cargo for cheaper.

**Comment by coolsurf6** [comment]
👀

**Comment by MCterra10** [comment]
why tho? just do xenobio

**Comment by MCterra10** [comment]
people always say "this will make cargo more important" when in reality, all cargo ever does is buy guns, regardless of how much shit is available to them

**Comment by ZombiesVsPlants** [comment]
Something for xenobiologists to spend money on if they can't get the extracts they want or allows cargo to buy cool stuff but not the REALLY cool crossbreeds

**Comment by ZombiesVsPlants** [comment]
Oh ok

**Comment by TheFakeElon** [comment]
Aww

**Pull request closed without merging**
