### PR TITLE
Captains Hat Tweak

### PR DESCRIPTION
**Pull request by MrLostman**
##  About The Pull Request
Makes captains hat space worthy

## Changelog
:cl:
tweak: makes captains hat space worthy
/:cl:

### CODE REVIEW

**Comment by Mick1299** [comment]
Who needs a helmet when have ultimate faith in your authority over everything, even space itself

**Comment by zeskorion** [comment]
y

**Comment by thelaughingbomb** [comment]
because style

**Review by MCterra10 — CHANGES_REQUESTED** [review]
at least be consistent and do this for the captain's beret too.

**Review by MCterra10 — APPROVED** [review]

**Pull request merged**
