### PR TITLE
[MIRROR] Paper Fixes

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/2860
--------------------
https://github.com/tgstation/tgstation/pull/52470/

Fixes stamps with paper and some other issues, like not being able to examine paper on airlocks

:cl:
fix: Paper stamping fixed
fix: Examining paper on airlocks works
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
remirror

**Comment by MCterra10** [comment]
it's failing because we don't have tgui4,

**Comment by MCterra10** [comment]
remirror

**Comment by MCterra10** [comment]
merging, the compile bot will fix

**Pull request merged**
