### PR TITLE
Smes tweak

### PR DESCRIPTION
**Pull request by Ohagi-Chan**
## About The Pull Request
Removes the SMES buffer from roundstart AuStation.dm, requiring engineers to actively set up a buffer of their own if they want to protect the station from power outages.

The station still has 4.5e6 joules in reserve, so the time before the first blackout is unchanged, but should the SM (and solars and whatever else) stop running, the station will immediately blackout. Areas with their own SMES are protected from this.

Finally, the emitters now have their own SMES that will provide them with 40KW even if the rest of the station runs out of power. The emitter SMES is charged by the station's powernet but does not give anything back to it.

## Why It's Good For The Game
Makes engineers work harder to provide a safe station to the masses.
It's a buff because now the emitters won't run out of power just because nobody set up.
It's a nerf because engineers now have to add a terminal and feed to the remaining old SMES if they want the station protected against blackouts when the SM is turned off.

## Changelog
:cl:
add: a new SMES to the emitter room, east of the SM
del: removed 2 of the SMES from the power monitoring room
del: removed the terminal attached to remaining SMES in the power monitoring room
tweak: changed the layout of cables connecting the SM to the main grid, now the SM is plugged straight in
tweak: changed the default charge of the remaining SMES in the power monitoring room - now it has 3x the charge
/:cl:

### CODE REVIEW

**Comment by Ohagi-Chan** [comment]
ok, that's a lot better, I think.

**Comment by Ohagi-Chan** [comment]
sorry for upsetting you, @totallynotkatfood , @thelaughingbomb

**Comment by MCterra10** [comment]
Bruh, terra no like, this is cringe. There's heaps of rounds where there's no engis, at least the SMES gives some window of time for an assistant to get a suit and set up solars

**Comment by MCterra10** [comment]
Atmos consumes a stupid amount of power and will die before the engineers can actually set power up.

**Comment by Ohagi-Chan** [comment]
> Bruh, terra no like, this is cringe. There's heaps of rounds where there's no engis, at least the SMES gives some window of time for an assistant to get a suit and set up solars

that's still in.  it really is.
the station still has 4.5e6 energy to burn through before the first blackout.
difference is, the emitters will still have power when the blackout hits.

**Comment by MCterra10** [comment]
I think you're underestimating how fast APCs discharge once the SMESs die (or suddenly don't exist)

**Comment by Ohagi-Chan** [comment]
Annotation 2020-08-20 175631

**Comment by MCterra10** [comment]
Also total energy means nothing and just serves to inflate values. The majority of APCs (barring I think, atmos and gravity) have 10kJ batteries.

**Comment by MCterra10** [comment]
I no like
Sorry fam

**Comment by Ohagi-Chan** [comment]
Sorry @MrLostman he disagree that we need to get rid of them.

**Pull request closed without merging**
