### PR TITLE
Austation Security, Maint, Vault, AI Upload map change

### PR DESCRIPTION
**Pull request by mudzbe**
## About The Pull Request
Changes Austation's Security, Maint, Vault and AI Upload.

Downsized the execution chamber a bit to make room. Moved the gulag shuttle to perma, this took up space and now this creates a possibility of breaking into the shuttle from space which could be interesting. Where the shuttle was originally was a waste of space and was ugly. With the space created by moving the shuttle, more maints were added. The surgery room from perma was incorporated into the infirmary and it now has a cool window to space.
screenshot

Moved the security escape pod to the firing range (which was a waste of space). This makes the pod more accessible to security and makes it more relevant, but was mainly done to make perma look better from space.
screenshot3

Moved toolstorage to the sec hallway, this balances out the hallway north of the bridge, it had nothing there the average crew were interested in. The AI upload and vault now has it's own lobby area with a motion detecting camera. It is very accessible from maints, but gives the AI more warning if someone is trying to break into the vault or AI upload. Both rooms are also able to be broken into from space. Overall this makes more planning required to break into either room, but still nonetheless doable. It didn't make much sense that the nuke was in this random space behind tool storage and cargo and to a lesser extent why the AI upload was in a random bit of hallway.
screenshot2

Here is the complete picture of the changes, it is fully up to date:
screenshot4

## Changelog
:cl:
tweak: Austation Security, Maint, Vault, AI Upload map change
/:cl:

### CODE REVIEW

**Comment by Singularity69** [comment]
add in a bondage room in security please

**Comment by mudzbe** [comment]
How

**Comment by mudzbe** [comment]
teeestmerge

**Comment by MCterra10** [comment]
testmerging, we'll see how people like it

**Comment by mudzbe** [comment]
@MCterra10 job done

**Comment by Effectism** [comment]
I'm not a fan of these changes so far. They look bad, and I can't see how they'd improve the map; it feels like change for the sake of change.

**Comment by mudzbe** [comment]
> I'm not a fan of these changes so far. They look bad, and I can't see how they'd improve the map; it feels like change for the sake of change.

I’m sorry who are you

**Comment by MCterra10** [comment]
> 
> 
> I'm not a fan of these changes so far. They look bad, and I can't see how they'd improve the map; it feels like change for the sake of change.

I agree, as do the server admins. the changes just feel unnecessary. They don't add anything of value to the map, and in fact just adds mistakes and weirdness like the directional window in the brig infirmary.

**Pull request closed without merging**
