### PR TITLE
[MIRROR] gives engi borgs a holofan projector

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/2362
--------------------
## About The Pull Request

title

## Why It's Good For The Game

why shouldn't they have it

also because @ Wilchenx wanted it

## Changelog

:cl:
add: Added the holofan to engi borgs
/:cl:

### CODE REVIEW

**Comment by thelaughingbomb** [comment]
hmm, deja vu

**Comment by coolsurf6** [comment]
AHAHAHAHAHAHA

**Comment by coolsurf6** [comment]
Speedmerge it lets go

**Comment by MCterra10** [comment]
LMAO
poor tlb, PR stolen

**Pull request merged**
