### PR TITLE
You can now lick people

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

title

## Why It's Good For The Game

~~this has nothing to do with terra what are you talking about~~

## Changelog
:cl:
add: Added licking
/:cl:

### CODE REVIEW

**Comment by jbox144** [comment]
Every day
we stray further to a cit port

**Review by MCterra10 — APPROVED** [review]

**Comment by amidoingitright** [comment]
this PR is giving me a first world problem, the problem of not having bleach to clean my eyes and the eyes of any poor bastard that reads this

**Comment by jbox144** [comment]
NO NO

**Comment by amidoingitright** [comment]
NOOOOOO

**Comment by jbox144** [comment]
NOOOOOOOOO TERRA WHY

**Comment by amidoingitright** [comment]
PLEASE UNMERGE

**Comment by jbox144** [comment]
FUCK

ITS NOT A JOKE. ITS REAL. AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH

**Comment by amidoingitright** [comment]
I DONT WANT THE CLOWN TO CUFF AND LICK ME EWWWWWWWWWWW


I HATED READING DREAD AND CIRCUSES THIS IS THE WORST

**Comment by thelaughingbomb** [comment]
revert please

**Comment by amidoingitright** [comment]
please revert terra or you wont be getting any [REDACTED]

**Comment by coolsurf6** [comment]
I'll fucking murder one everywhone who licks if you keep this cancer mate.

**Pull request merged**
