### PR TITLE
Gygaxes require silver and gold instead of diamonds (like before the rebase)

### PR DESCRIPTION
**Pull request by thelaughingbomb**
## About The Pull Request

Prior to the rebase gygaxes got a nerf to have their auto kick removed and then their cost got changed because of that, this PR brings that here.
## Why It's Good For The Game

Its a just like before the rebase.
## Changelog
:cl:
tweak: Gygaxes require gold and silver instead of diamonds
/:cl:

### CODE REVIEW

**Comment by coolsurf6** [comment]
Ok now that is kinda powerful. I'll be honest usually you can onyl make 1 gygax with the diamond you have, even at max upgrade unless miners went ham. But only silver and gold is a bit too cheap imo. Unless the amounts for those are high enough to compensate that is.

**Comment by MCterra10** [comment]
To be fair, I did nerf the shit out of gygaxes, as they no longer knock out the people they punch, and they can no longer run through walls, and they no longer auto-hit stuff in front of them when overloaded

**Comment by coolsurf6** [comment]
I guess that makes sense. Time to spam gygaxes yeehaw

**Comment by BowStache** [comment]
Gamer time 😎

**Comment by MCterra10** [comment]
can't spam them any more than you can spam durands

**Pull request merged**
