### PR TITLE
removes weird Citadel-level flavourtext HRP shit

### PR DESCRIPTION
**Pull request by YakiAttaki**
## About The Pull Request
i genuinely don't even understand why this was an addition. literally Citadel station level flavour text shit.
yes, i did web edit this, because i'm too lazy to clone the source again and update my local branch.

## Why It's Good For The Game
we're not Citadel and we're LRP. having "marriages" is fucking weird and unnecessary.

## Changelog
:cl:
del: removed "rings" from character set up preferences. blech.
/:cl:

### CODE REVIEW

**Comment by jbox144** [comment]
ye boi

**Comment by YakiAttaki** [comment]
i swear to god if travis fails i'm going to jump off a bridge

**Comment by MCterra10** [comment]
lol hoes mad

**Comment by MCterra10** [comment]
also you did this incorrectly and missed files, btw

**Comment by YakiAttaki** [comment]
whhat did i miss?

**Comment by YakiAttaki** [comment]
i'd look at the files changed in the pr you made but uh.

_cough_ cringe host stealth PRs shit _cough_

**Comment by MCterra10** [comment]
inb4 you start using this

**Comment by YakiAttaki** [comment]
i'm not going to

**Comment by YakiAttaki** [comment]
why would i put effort into removing something if im going to use it

**Pull request closed without merging**
