### PR TITLE
[WIP] Eating without a table is a war crime

### PR DESCRIPTION
**Pull request by Effectism**
steamuserimages-a akamaihd net

## Changelog
:cl:
tweak: Eating without a table is now a war crime
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
This'll be funny for like, one round, then it's just going to be a pain in the ass. Perhaps it could be locked behind an admin secret or something

**Comment by MCterra10** [comment]
whoops wrong button ree

**Comment by BowStache** [comment]
Ok boomer

**Comment by Effectism** [comment]
I'll see to making it a random event later

**Comment by Effectism** [comment]
This shitty meme PR isn't funny enough to warrant not being completely _modular_
Maybe when I learn2code better.

**Pull request closed without merging**
