### PR TITLE
Roundend channel now display antag infos

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

yep

## Changelog
:cl:
add: adds antag info to roundend channel
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
please use the PR description template, not just "yep" thanks

**Comment by jupyterkat** [comment]
this doesn't directly affect anything in the game

**Comment by TheFakeElon** [comment]
you rarely give an actual description for your PRs smh

**Comment by jupyterkat** [comment]
because most off the times the title basically described everything

**Comment by TheFakeElon** [comment]
You could at least do the CL 😔

**Comment by jupyterkat** [comment]
alrighty 😔

**Review by TheFakeElon — APPROVED** [review]
Ty

**Pull request merged**
