### PR TITLE
Fitness holodeck

### PR DESCRIPTION
**Pull request by Mick1299**
## About The Pull Request
Adds a Gym holodeck, complete with workout equipment, boxing gloves and bags, and a motivational trophy and champs belt.

## Why It's Good For The Game
People wanted a fitness area, bomb suggested it be a holodeck

## Changelog
:cl:
add: Fitness holodeck, called "The Gym"
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
ohhh fuckkkk, not centcom changes fuck fuck fuck fuckkk

**Comment by MCterra10** [comment]
make it a fitness area, I overule jojo. I don't wanna change centcom holy fuck

**Comment by TheFakeElon** [comment]
F

**Comment by coolsurf6** [comment]
F

**Pull request closed without merging**
