### PR TITLE
Adds the cake printer

### PR DESCRIPTION
**Pull request by totallynotkatfood**
## About The Pull Request

Adds the cake printer, which scans the item you insert into it and creates a cake that takes the form of the item, except for the description of the item. It takes synthetic cake batter as fuel, which is 15u flour, 15u milk and 5u of astrotame.

## Why It's Good For The Game

even more chef buff(tm)

## Changelog
:cl:
add: Added cake printer
add: Added cake batter reag
/:cl:

### CODE REVIEW

**Comment by Ohagi-Chan** [comment]
So
Why bother making regular cakes now?

**Comment by totallynotkatfood** [comment]
Regular cakes doesn't need a research-required machine to make

**Comment by ZombiesVsPlants** [comment]
Me like

**Comment by TheFakeElon** [comment]
What if emagging the cake dispenser made them poisonous :winrar:

**Comment by MCterra10** [comment]
I agree, there is literally no point making regular cakes with this.
at least with the bread machine, the bread's main use is as a weapon, and has poor nutrition until higher levels.

**Comment by totallynotkatfood** [comment]
nope, it's nutrition is the same for every weight classes

**Comment by TheFakeElon** [comment]
What Terra is saying is that this machine makes normal cakes pointless. Giving less things for the chef to do.

**Comment by MCterra10** [comment]
bruh we already have bread. I really don't think we need 9 changed files to make haha funny cake

**Comment by ZombiesVsPlants** [comment]
bro this was cool smh smh

**Pull request closed without merging**
