### PR TITLE
[MIRROR] The Defib Nerf (Defibs are no longer a 10 second paralyze)

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/tgstation/tgstation/pull/47675
--------------------

## About The Pull Request
Defib stun now knocks down for 7.5 seconds.
Adds a new status effect, 'convulsing'.
Convulsion makes you drop your inhand item with a 40% chance every time Life is triggered.
Defib gives you 15 seconds of convulsion.

## Why It's Good For The Game
Defibs survived the stun baton purge of hardstunning. They instantly stun you for 10 seconds and have a 5 second recharge time, not to mention they deal 50 stamina damage and can for some reason stun borgs. 
I wanted to keep them as being a superior choice over the stun baton, as they take up a belt slot or back slot, two hands, and preparation. Simply making them a shitty stun baton would mean that everyone would just make a stunprod or stunbaton without bothering to emp/emag the defib whatsoever, ruining the point of their existence.

## Changelog
:cl:
balance: Emagged defillibrators now knock people down for 7.5 seconds, deal 55 stamina damage, and convulse for 15 seconds, They don't stun borgs anymore.
add: New status effect: Convulsions. 40% chance to drop your inhand item every tick.
balance: Harm intent defillibrator heart attack takes half as much time.
fix: ERT preproom no longer has a syndicate defillibrator.
add: It now has a nanotrasen elite defillibrator, extremely high quality and definitely not a repaint of a syndicate defib.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
bad pr dont merge this

**Comment by MCterra10** [comment]
Why is that?

**Comment by MCterra10** [comment]
@carlarctg

**Comment by MCterra10** [comment]
Fuck this shit I'm merging since another PR is using convulsions now

**Comment by carlarctg** [comment]
coders ignoring feedback

**Pull request merged**
