### PR TITLE
[MIRROR] Fixes maps' pipes a bit

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/3125
--------------------

## About The Pull Request

My increased knowledge on pipenet code has made me anxious about the state of affairs around our maps' pipes. This PR aims to fix all of them, which is mostly "fixing til the game stops yelling at me". The changes should be small because unlike #3052 this aims to fix that is explicitly broken (or prone to break) and/or possible to cause problems at the pipenet code. This PR also shows that Kilo had the best piping, while Box had the worst.

## Why It's Good For The Game

Mis-pipings are just bad in themselves, but some serious mis-pipings like duplicate pipes can cause harddels by causing duplicate pipenets. This PR should help reduce harddels caused by bad mapping. (I am looking at you Box and Pubby)

## Changelog
:cl:
fix: fixed quite a lot of pipes on every map (except Kilo which only had one trivial problem) to improve experience and performance
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
map conflicts

**Comment by TheFakeElon** [comment]
_reeeeeeee_

**Comment by MCterra10** [comment]
conflict in *delta*?? what

**Comment by TheFakeElon** [comment]
not sure what's going on there.. We've never touched delta, not that part at least

**Comment by TheFakeElon** [comment]
remirror

**Comment by MCterra10** [comment]
ugh, I'll reset it. there's no reason for delta to conflict at all, unless we've missed a PR or something

**Pull request merged**
