### PR TITLE
Fumo

### PR DESCRIPTION
**Pull request by mudzbe**
## About The Pull Request

Adds a fumo.
cirnu

## Changelog
:cl:
add: Added a fumo plushie
/:cl:

### CODE REVIEW

**Comment by amidoingitright** [comment]
those errors dont seem to be a result of this PR

**Comment by mudzbe** [comment]
they're to do with the austation.dme, it automatically changes it and normally I just wouldnt commit austation.dme but I've made changes there so I need to

**Review by TheFakeElon — APPROVED** [review]
image

**Comment by Mick1299** [comment]
maintainer bias 😠

**Comment by mudzbe** [comment]
gnuuueeee

**Pull request merged**
