### PR TITLE
[PORT] Ports Orbital Station

### PR DESCRIPTION
**Pull request by PapaSejd**
## About The Pull Request

Ports PerpetuaStation's _Orbital Station_. Inspired by maps such as Charlie Station and LifeWeb's similarly named gamemode, this station is meant to be a low-pop map full of PvE action, ranging from exploration of the ruins, to fighting mobs inhabiting said ruins to repairing and reclaiming what was once the original station. Made for pops between 0 to 40 players, this may change in the future as more ruins and structures are added.

image

**NOTE:** This map is very WIP. I will be following up with many more PRs that will port updates from Perpetua's version of this map. More ruins and improvements will be added.

image

_Map with overlays to show areas, everything not highlighted is ruins or hallways_
## Why It's Good For The Game

Originally, this map was created for Perpetua due to its average player pop which would be 5-15 players. Maps like BoxStation and MetaStation were too large for even this low of a server pop, so this map was created to give an alternative that is more compact, allowing smaller crews to interact, and have PvE features that allow pops even as low as 1 person to have something to do. 

:cl:
Ported: OrbitalStation.dmm
/:cl:

### CODE REVIEW

**Comment by Mick1299** [comment]
You need to map merge your map, read this
https://tgstation13.org/wiki/Map_Merger

**Comment by MCterra10** [comment]
I can hear bee reeeing because you didn't port this upstream

**Comment by PapaSejd** [comment]
Aight its been map merged, should cause no issues, tho I did break my entire git doing it

**Comment by coolsurf6** [comment]
I can probably see this getting yoinked upstream.

**Comment by TheFakeElon** [comment]
vault is only one wall from open space and another from atmos

**Comment by Crossedfall** [comment]
reeeeeeeeeeeeeeee

**Comment by PapaSejd** [comment]
nvm kat PR'ed this upstream

**Comment by PapaSejd** [comment]
woops again

**Comment by MCterra10** [comment]
config updated

**Pull request merged**
