### PR TITLE
Cursed oxygen tank tendril loot

### PR DESCRIPTION
**Pull request by jbox144**
## About The Pull Request

A simple tendril loot concept: The cursed oxygen tank provides an infinite supply of oxygen. Due to the small size of the tank, it can't be used for industrial applications such as supplying an atmosphere, but for a personal air supply it's perfectly fine, and free's up a slot on one's loadout.

If it ruptures, it will explode violently.

## Why It's Good For The Game

Tendril loot that isn't a tech disk.

## Changelog
:cl:
add: Added the cursed oxygen tank, an emergency oxygen tank providing infinite oxygen for free.
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
if it's "cursed" I think it would be neat if it had a downside.

**Comment by TheFakeElon** [comment]
then again, it's not _really_ useful as it is. I doubt people would choose to use it if it was significant

**Comment by MCterra10** [comment]
make it undroppable and we have a deal.

**Comment by YakiAttaki** [comment]
ohoho, i like that. really not that difficult, just give it the no_drop trait

**Comment by jbox144** [comment]
sounds good

**Comment by MCterra10** [comment]
You've got a compilation error, might wanna look into that

**Comment by jbox144** [comment]
I'll fix it tomorrow:tm:

**Comment by ZombiesVsPlants** [comment]
No drop? Does that mean it can't be moved from the pocket or does it mean you can't move it from your hand?

**Comment by TheFakeElon** [comment]
Includes

**Comment by MCterra10** [comment]
waiting on conflicts

**Comment by MCterra10** [comment]
travis fail is unrelated.

**Pull request merged**
