### PR TITLE
D e a t h   s k y

### PR DESCRIPTION
**Pull request by TheFakeElon**
## About The Pull Request

Adds "Admiral Deathsky" a modified griefsky that is armed with a pulse rifle, better armour and increased block chance. Available for nuclear operatives in the form of a beacon.  

## Why It's Good For The Game
gives nukeops and loneops something to cause more of a distraction... 

a d m i n b u s   b o t

## Changelog
:cl:
add: adds Admiral Deathsky. A nukeop "tool"
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
oh no

**Comment by MCterra10** [comment]
if this is a nukie item it should literally be like 30 TC or some shit

**Comment by TheFakeElon** [comment]
hnnng, it will attack nukies too though. a bulldog shotgun is way more effective for killing

**Comment by MCterra10** [comment]
re-running travis

**Comment by zeskorion** [comment]
is this even tested

**Comment by TheFakeElon** [comment]
yes

**Comment by TheFakeElon** [comment]
uhh, wall smashing does NOT work. but that's probably for the best

**Comment by MCterra10** [comment]
@zeskorion lmfao ironic considering autofire is still broken

**Comment by TheFakeElon** [comment]
In hindsight I could have made this a lot better lol

**Pull request merged**
