### PR TITLE
tweak sec hardsuits (and hos)

### PR DESCRIPTION
**Pull request by amidoingitright**
## About The Pull Request

tweaks security hardsuits to provide flashbang protection (this will not make felinids immune to flashbangs)

## Why It's Good For The Game

This used to be a thing on TG if i remember correctly, so i remade it here, enjoy

## Changelog
:cl:
tweak: sec hardsuits now provide bang protection
/:cl:

### CODE REVIEW

**Comment by amidoingitright** [comment]
the latest commit name is confusing, and not true, i dont know why it says that

**Comment by coolsurf6** [comment]
Should be done upstream.

**Comment by amidoingitright** [comment]
actually yes, i'll make a PR upstream

**Comment by Mick1299** [comment]
Pretty sure this would give anyone wearing the suit with the helmet on +2 bang protection.

**Comment by amidoingitright** [comment]
its a change to the hardsuits helmet though

**Comment by Mick1299** [comment]
Ah wait, should have read that a little closer. Its +1 for Sec hardsuit helmet and +1 for HoS hardsuit helmet

**Comment by amidoingitright** [comment]
dont merge this as i've put a PR in for it upstream

**Pull request closed without merging**
