### PR TITLE
Sandy Austation map

### PR DESCRIPTION
**Pull request by Ohagi-Chan**
## About The Pull Request

Adds Sandy_Austation.dmm map
Also changes the default uniform to include a snowman suit

## Why It's Good For The Game

A change of scenery

## Changelog
:cl:
add: Added Sand_Austation.dmm
tweak: The ambient temperature of AuStation is now 40 degrees.
server: The map is not playable by default.  You'll need to enable it in configs.
/:cl:

An overview of the differences between this map and regular Austation.dm
Screenshot 2020-12-28 030104

### CODE REVIEW

**Comment by TheFakeElon** [comment]
Isn't it supposed to be summer here? Should we really be giving in to the Americans smh

**Comment by Ohagi-Chan** [comment]
> Isn't it supposed to be summer here? Should we really be giving in to the Americans smh

True. I don't have an argument to meet that.
That said, I'm not going to hand this map to Bee and I doubt they want it.

**Comment by MCterra10** [comment]
BAHAHHAHAH

**Comment by MCterra10** [comment]
make it all sand instead and add grills everywhere

**Comment by Ohagi-Chan** [comment]
> make it all sand instead and add grills everywhere

I may do this later tonight. If I don't bother, just close it.

**Comment by MCterra10** [comment]
eh, feel free to make it more australian, but I'll still end up testmerging it for laughs

**Comment by Ohagi-Chan** [comment]
Are we still waiting on any changes to this?

**Comment by TheFakeElon** [comment]
Extra social credits if you make the station 40c

**Review by TheFakeElon — APPROVED** [review]

**Comment by Ohagi-Chan** [comment]
> Extra social credits if you make the station 40c

Easily done.  Will do in about 6 hours.

**Comment by TheFakeElon** [comment]
@MCterra10 config

**Comment by MCterra10** [comment]
closing now. most people hate it lmaoo

**Pull request closed without merging**
