### PR TITLE
Revert "[MIRROR] Moves Mech Weapons to Sec Protolathe"

### PR DESCRIPTION
**Pull request by YakiAttaki**
## About The Pull Request
puts the mech weapons back in robo

## Why It's Good For The Game
this PR is specifically addressing an MRP rule. we're not MRP. this will just lead to people breaking into sec even more just to get mech weapons.

## Changelog
:cl:
balance: put the mech weapons back into robo
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
people don't need weapons unless there's a significant threat to the station, probably the most unfun experience as an antag you can have is getting murdered by some roboticist because he spent 10 minutes (probably much less) in his autism forts clicking parts together.

Every other old science weapon is printed at security, why should even stronger weapons be exempt? Tot robos now have to actually be smart getting their gamer weapons.

**Comment by thelaughingbomb** [comment]
traitor robos can emag the mech disabler to make it lethal btw

**Comment by YakiAttaki** [comment]
> people don't need weapons unless there's a significant threat to the station

you say this like we're a roleplaying community.

**Comment by Kalvinalvaro** [comment]
Aren't we NRP with LIMITED powergaming and validhunting rules? also im tired of getting robusted with gamer mech with no way of killing it except for EMP 30 minutes into the round cause im anteg

**Comment by TheFakeElon** [comment]
Yeah, and it’ll take much more than a box of emp grenades and an implant to kill mechs usually. You will have a lot of trouble killing a mech unless you’ve got a pretty decent shotgun or got your grubby hands on an ion rifle.

FYI you can still kill people with mechs without power gaming the sec protolathe, just stamcrit them with a disabler and punch them

**Pull request closed without merging**
