### PR TITLE
[MIRROR] Refactors cable and disposal pipe construction/deconstruction code to improve performance

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/3285
--------------------

## About The Pull Request

(In case you are curious, my branch names are selected from what I was listening when I created the branch. Maxim Vengerov 1992 recording, it was.)

1. Every cable structure creates and stores a cable coil item since its creation...
1.1. when it is only needed for destruct item drop.
1.2 And every disposal pipe structure also does the same thing with disposalconstruct structure!
2. So, do you know how many cables and disposal pipes are there in a map?
3. And, do you know atmosmachineries already create broken parts in situ? (since tgstation/tgstation#21992 thx MSO)
4. Therefore, this PR fixes the problem by making them create post-destruction objects in situ too, like atmosmachineries!
5. Additionally, the PR ended up making the code simpler.

Finally  a downstream note: AU should revert austation/austation#2311 and make changes to austation/austation#2028 to mirror this PR.

## Why It's Good For The Game

To summarize, this should shorten the world init time (around 1%), and reduce memory usage a little: around 10MB. ~~why do you use so much memory on these, BYOND~~

## Changelog
:cl:
refactor: refactored cable and disposal pipe construction/deconstruction code to remove ugly legacy code
fix: removal of said ugly legacy code improved performance a bit
fix: and fixed cable color bugs
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
remirror

**Comment by MCterra10** [comment]
this *probably* works

**Comment by MCterra10** [comment]
I might testmerge

**Comment by MCterra10** [comment]
looks good

**Pull request merged**
