### PR TITLE
You can build plating on dug asteroid surfaces

### PR DESCRIPTION
**Pull request by Ohagi-Chan**
## About The Pull Request
Permits player to build plating on lavaland basalt surfaces by applying a floor tile.  Previously this would act like all other plating turfs and just cover the basalt with a plasteel floor.

**Please note that this change has not been modularised.  I will need to make some adjustments if you want it to be**

## Why It's Good For The Game
Plating tiles are required for properly building bases as you can only build certain structures (like terminals) on top of plating.  Previously it was impossible for lavaland inhabitants to change basalt surfaces to plating without using an RCD to dig up the turf to reveal lava, then build a floor over the lava.
This change lets you get started on your base building without the entire plan depending on the RCD tool.

## Changelog
:cl:
tweak: plating can be built on basalt using a floor tile
/:cl:

### CODE REVIEW

**Comment by Ohagi-Chan** [comment]
I should probably expand the turfs that follow this behaviour to include ashplanet, beach, ice and snowed

**Review by MCterra10 — CHANGES_REQUESTED** [review]
fyi, you need to add a check for "super hot lava" that I setup around the syndicate base, because tiles should not be placeable on that.

**Comment by Ohagi-Chan** [comment]
Won't be a problem, this changes
turf/open/floor/plating, while lava is 
/turf/open/lava.

I can't even cover up regular lava when I did testing.

**Comment by TheFakeElon** [comment]
The title is a bit misleading as anyone can build there, could I suggest making it so lavaland tiles need to be dug up with a shovel before placing a tile on it?

**Comment by TheFakeElon** [comment]
Fix your CL

**Comment by Ohagi-Chan** [comment]
Later. Not home.

**Review by MCterra10 — CHANGES_REQUESTED** [review]
just edit the original proc and comment your changes please. I hate reimplementing large procs because it means if bee makes a change, we have to mirror that change to our copy of the proc, which is more work than just resolving the merge conflict.

**Comment by Ohagi-Chan** [comment]
Can do

**Review by TheFakeElon — APPROVED** [review]

**Review by MCterra10 — APPROVED** [review]

**Pull request merged**
