### PR TITLE
Make Botany Great Again

### PR DESCRIPTION
**Pull request by MrLostman**
## About The Pull Request
Reverts botany salt nerfs,

Separated Chems now work on squish.
Hypodermic Prickles now work on hit and on throw.
Earth Blood has had druggy removed and brain damaged reduced.

Feel free to ask for other nerfs to be reverted.

## Why It's Good For The Game
Doesn't put botany above other jobs viro/xeno/mining. Gives botany way more options in offensive and healing plants.

## Changelog
:cl:
tweak: separated chems work on squish.
tweak: hypodermic prickles work on hit and on throw.
tweak: earth blood has had druggy removed and brain damage lowered.
/:cl:

### CODE REVIEW

**Comment by MrLostman** [comment]
Buff or bust

**Comment by MCterra10** [comment]
bruh I'd trade buggy and jitter for the removal of the brain damage

**Comment by MCterra10** [comment]
it makes it useless for healing without mannitol because it'll give you brain traumas

**Comment by MCterra10** [comment]
conflict

**Pull request merged**
