### PR TITLE
Incinerator pump cams

### PR DESCRIPTION
**Pull request by totallynotkatfood**
## About The Pull Request

title

## Why It's Good For The Game

AIs can now control the pumps and operate the turbine for power

## Changelog
:cl:
add: Added more cams to the Incinerator in the most used maps and name them correctly in some
/:cl:

### CODE REVIEW

**Comment by totallynotkatfood** [comment]
It's the same mood bonus as hugs and also wears off in 2 mins

**Comment by TheFakeElon** [comment]
God please no, they're not built in for a reason.

**Comment by MCterra10** [comment]
standby, there will probably be conflicts after I merge the piping changes.

**Comment by Mick1299** [comment]
After a discussion with Kat, I'll add this to my piping pr to save them a mapping conflict headache

**Comment by TheFakeElon** [comment]
Aye

**Comment by TheFakeElon** [comment]
Oops, only changed for austation map, my bad

**Comment by MCterra10** [comment]
no map changes to stuff other than austation now. conflicts aren't worth it now that we have our own sandbox.

**Pull request closed without merging**
