### PR TITLE
The Dawson Memorial Emote

### PR DESCRIPTION
**Pull request by YakiAttaki**
## About The Pull Request
Dawson was arguably the most terrifying force to hit AuStation in the year and a day that it's been running. He deserves to be remembered in some fashion.

## Why It's Good For The Game
An emote that we've sorely needed. R.I.P. Dawson. He's not dead or anything, he just doesn't play SS13 anymore.

## Changelog
:cl:
add: NanoTrasen has now authorised you dumbasses to dab.
/:cl:

### CODE REVIEW

**Comment by YakiAttaki** [comment]
uh not sure why that failed

**Comment by YakiAttaki** [comment]
oh i think i know one sec

**Comment by MCterra10** [comment]
I remember a server added one of these that made you actually tilt when you dabbed, let me see if I can find the PR link

**Comment by YakiAttaki** [comment]
oh holy shit, thats neat as

**Pull request merged**
