### PR TITLE
Revert "You can now lick people"

### PR DESCRIPTION
**Pull request by thelaughingbomb**
Reverts austation/austation#2346

Reverts fetish content.

### CODE REVIEW

**Comment by jbox144** [comment]
tlb save us

**Comment by MCterra10** [comment]
"no kneejerk revert PRs"
~Oranges

**Comment by jbox144** [comment]
FUCK

**Comment by coolsurf6** [comment]
Austation is getting worse and worse...

**Comment by thelaughingbomb** [comment]
terra must of pressed the wrong button and closed it

**Comment by MCterra10** [comment]
Don't worry, I have a revert commit staged on my local branch, I just want to see people get mad

**Comment by coolsurf6** [comment]
naaah keep this, I wanna be able to murderbone without any reprecussion aside from mental damage of using the licking verb.

**Comment by MCterra10** [comment]
Your wish is my command

**Comment by coolsurf6** [comment]
Alright I had my fun with a bit of a boom, remove this cancer.

**Pull request closed without merging**
