### PR TITLE
[PORT] Cybernetic organs

### PR DESCRIPTION
**Pull request by amidoingitright**
https://github.com/tgstation/tgstation/pull/52142 

https://github.com/tgstation/tgstation/pull/48714

## About The Pull Request

Ports many organs and sprites from TG (mostly sprites)
## Why It's Good For The Game

Adds more funky organs with special attributes I.E self healing albeit at a far reduced rate 0.5 (excluding ears which regen at 1.5 the organ healing rate)
also cool ass looking organs
## Changelog
:cl: Alterist Kriskog
add: Esoteric organs including, ears, heart, liver, lungs and the stomach
add: cybernetic cat ears, because i'm still trying to get that added in
imageadd: ported the cool ass looking sprites from TG for said organs
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
please link the original PR(s) when porting. Crediting the author(s) next to the first :cl: would be nice too :p

**Comment by amidoingitright** [comment]
After scouring tg I didn't find the guy who made the tier3 organ sprites

**Comment by amidoingitright** [comment]
curious, seems that that PR brought the sprites. Which means that i have given credit where credit due

**Comment by amidoingitright** [comment]
> please link the original PR(s) when porting. Crediting the author(s) next to the first :cl: would be nice too :p

PR has been fully credited

**Comment by amidoingitright** [comment]
Can you put a do not merge tag on this i think I might port more than just sprites

**Comment by amidoingitright** [comment]
fun learning experience, but in execution the organs are somewhat of a downgrade

**Pull request closed without merging**
