### PR TITLE
[MIRROR] [Port] tgui: Refactor Asset Delivery

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/3220
--------------------
Ports: https://github.com/tgstation/tgstation/pull/54895

----

## About The Pull Request

Needs testing on IE8!

This refactor unifies loading of scripts and stylesheets under a single API, which looks like this:
```js
Byond.loadJs(url);
Byond.loadCss(url);
```
These functions are not only used in tgui bundle to load dynamic assets (like font-awesome icons), but also in `tgui.html`, where bundles themselves are loaded.

Both functions have a little bit of network resilience, and will keep trying to load for 10 seconds. If they still fail to load, user will see a blue screen of death instead of a white screen, so this is a definite improvement.

Bluescreen stylesheet is also included directly in `tgui.html`, to make sure it's properly functioning even when scripts/stylesheets fail to load.

I did not notice any slowdown from using `Byond.loadJs(url)` instead of `<script src="url"></script>` which is pretty nice.
## Miscellaneous

* Updated VSCode configuration and installed a few Yarn Berry SDKs to improve intellisense and re-enable eslint.
* Fixed printing of an initial update payload in tgui-dev-server.

## Changelog

:cl:stylemistake 
refactor: TGUI will keep trying to load for 10 seconds in case of a network problem and will show a bluescreen if it completely fails.
fix: This hopefully fixes the whitescreen problem.
/:cl:

### CODE REVIEW

**Comment by Crossedfall** [comment]
This requires a TGUI recompile

**Comment by TheFakeElon** [comment]
thanks

**Comment by MCterra10** [comment]
I'm forcing a merge, the bot will rebuild everything

**Comment by MCterra10** [comment]
it's merged but didn't register

**Pull request closed without merging**
