### PR TITLE
Improves crew moral via whipping

### PR DESCRIPTION
**Pull request by Mick1299**
## About The Pull Request
Adds a minor +1 mood boost for 4 minutes to those whipped by the chain of command.

## Why It's Good For The Game
Whippings will continue until morale improves

## Changelog
:cl:
add: Small mood boost from being attacked by the chain of command
/:cl:

### CODE REVIEW

**Comment by jupyterkat** [comment]
horny detected

**Comment by ZombiesVsPlants** [comment]
W H A T  T H E  F U C K  I S  T H I S ?

**Comment by Singularity69** [comment]
Speedmege

**Comment by MCterra10** [comment]
honestly 10/10 PR

**Review by MCterra10 — APPROVED** [review]

**Pull request merged**
