### PR TITLE
Arrival shuttles now includes tiny fans

### PR DESCRIPTION
**Pull request by totallynotkatfood**
## About The Pull Request

title

## Why It's Good For The Game

moron proofing the shuttles

## Changelog
:cl:
add: Adds tiny fans to arrivals shuttles
/:cl:

### CODE REVIEW

**Comment by Mick1299** [comment]
That reminds me, can you add invisible tiny fans to the centcomm dock. It depressurised every round when the escape shuttle departs from centcomm

**Comment by totallynotkatfood** [comment]
I'll do this upstream, see if it gets merged

**Comment by MCterra10** [comment]
aight

**Comment by totallynotkatfood** [comment]
Upstream merged, closing pr

**Pull request closed without merging**
