### PR TITLE
Plasmacutter revert

### PR DESCRIPTION
**Pull request by Ohagi-Chan**
## About The Pull Request
reverts the plasmacutter nerf introduced in https://github.com/austation/austation/pull/2489

plasmacutters don't take 20 plasma ore chunks to refill anymore.
plasmacutters start full again.

## Why It's Good For The Game
it takes plasma material to build the cutter, why don't they have any in them?

## Changelog
:cl:
balance: plasmacutters start loaded when you print them
balance: plasmacutters only take 2 ore chunks to reload
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
based

**Comment by MCterra10** [comment]
I told yaki no kneejerk reverts.
imo this is a pretty good change for the game, but I wouldn't mind a decrease in refuel cost and bringing back prefueled cutters (you are right, they do cost plasma to make)

**Comment by Ohagi-Chan** [comment]
> I told yaki no kneejerk reverts.
> imo this is a pretty good change for the game, but I wouldn't mind a decrease in refuel cost and bringing back prefueled cutters (you are right, they do cost plasma to make)

Do you want a mid-way compromise then?
5 sheets/ 10 ores to recharge?

**Comment by TheFakeElon** [comment]
15 / 30 is fair

**Comment by Ohagi-Chan** [comment]
> 15 / 30 is fair

15/ 30 is harsher than Bee.

**Comment by TheFakeElon** [comment]
> 15/30 is harsher than bee

T’was the joke :p

> I’m suggesting a middle ground of 100 points

Eh, honestly I don’t see anything wrong with the original PR. This revert isn’t really needed imo.

You could make cutters start half full or something, just make sure buying a new cutter is more expensive than refilling one

**Comment by TheFakeElon** [comment]
Wait longer before reverting changes next time, like terra said, no kneejerk reverts. Plasma cutters were ridiculously strong and made mining completely effortless, you didn’t explain why this was a good change besides realism

**Review by TheFakeElon — CHANGES_REQUESTED** [review]
Wait longer before reverting changes next time, like terra said, no kneejerk reverts. Plasma cutters were ridiculously strong and made mining completely effortless, you didn’t explain why this was a good change besides realism.

Don’t override the entire object, there’s no need to override the name, description, icons etc. only the things you want to change

**Comment by TheFakeElon** [comment]
I’ll be closing this for now, feel free to PR this in a few weeks. Try using new cutters for a bit to see how it feels.

**Pull request closed without merging**
