### PR TITLE
removes weird Citadel-level flavourtext HRP shit - correctly done this time

### PR DESCRIPTION
**Pull request by YakiAttaki**
## About The Pull Request
i genuinely don't even understand why this was an addition. literally Citadel station level flavour text shit.
yes, i did web edit this, because i'm too lazy to clone the source again and update my local branch.

## Why It's Good For The Game
we're not Citadel and we're LRP/NRP. having "marriages" is fucking weird and unnecessary.

## Changelog
:cl:
del: removed "rings" from character set up preferences. blech.
/:cl:

### CODE REVIEW

**Comment by YakiAttaki** [comment]
at least let me see if travis runs correctly

**Comment by YakiAttaki** [comment]
travis CL passed, nice

**Comment by YakiAttaki** [comment]
can't believe I stopped watching T2 for this shit

**Comment by coolsurf6** [comment]
Looking at you, Kat.

**Comment by jbox144** [comment]
Ye boi

**Comment by MCterra10** [comment]
hoes mad

**Comment by totallynotkatfood** [comment]
lmao

**Pull request closed without merging**
