### PR TITLE
Adds professor membrane's gloves and labcoat

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

Adds professor membrane's gloves and labcoat to RD's locker.

## Why It's Good For The Game

More stuffs, credit to cit for some sprites

## Changelog
:cl:
add: Added more costumes and stuff
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
Citadel foreplay costume... hmmmmm

**Comment by TheFakeElon** [comment]
Hate to be a PR Nazi but It’s usually good practice to explain the PR a bit more, title is confusing for somewhat obvious reasons. Like, is there anyway to get this in game? If so where from, what does it do etc etc

**Comment by MCterra10** [comment]
why tho

**Comment by TheFakeElon** [comment]
>_chance to open a maint crate with reskinned cap armour and a sabre_

I was more thinking tendril loot or an expensive cargo crate

**Comment by jupyterkat** [comment]
Abandoned crates are not maint crate, @TheFakeElon

**Comment by TheFakeElon** [comment]
oop my bad :p

**Review by TheFakeElon — APPROVED** [review]

**Comment by ErwinSnowden** [comment]
this is literally citadel personal content PR tier. seriously?

**Comment by TheFakeElon** [comment]
ehhh, the “Kiara” stuff is literally someone else’s personal content (Not Au Kiara) from citadel. The professor membrane stuff is cool though.

**Comment by TheFakeElon** [comment]
Could you atomize the Kiara stuff into another PR or just remove it from this

**Comment by TheFakeElon** [comment]
Ty

**Pull request merged**
