### PR TITLE
MKA and Ion Thrusters

### PR DESCRIPTION
**Pull request by jbox144**
## About The Pull Request

Adds the MKA-27: Mech Kinetic Accelerator and Ion Thrusters for mechs. Pretty self explanitory. This PR also buffs the RCS module, reducing it's fuel usage considerably.

The MKA-27 is the mecha version of the standard Kinetic Accelerator. It's size allows it to have 160% upgrades. However, it's heavy duty application makes it slower to fire, but stronger (It's DPS is exactly the same as a normal KA). It's specifically tailored to low pressure environments, only doing 10% damage while in a pressurized environment (Compared to the normal KA's 25%)

## Why It's Good For The Game

Once again gives miners a reason to use mechs while mining, allowing them to perhaps even compete against mining gamer gear.

## Changelog
:cl:
add: Added the MKA-27: Mech Kinetic Accelerator
add: Added Ion Thrusters
balance: Significantly reduced the usage of RCS thrusters
add: Added new "Accelerator Tech" technology, prerequisite to the MKA and the Ion thrusters.
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
> putting a normal KA inside a mech and calling it mega

I’m thinking based

**Comment by TheFakeElon** [comment]
Jokes aside. This is neat but it looks like a downgrade from the plasma cutter, for mining purposes.

**Comment by jbox144** [comment]
> 
> 
> Jokes aside. This is neat but it looks like a downgrade from the plasma cutter, for mining purposes.

Who said you'll be pointing it at rocks?

**Comment by Mick1299** [comment]
looks like an alright alternative for robos who go mining. Plasma cutter does next to no damage against simple mobs, this would allow them to not run away at the first sign of a goliath

**Comment by jbox144** [comment]
> 
> 
> looks like an alright alternative for robos who go mining. Plasma cutter does next to no damage against simple mobs, this would allow them to not run away at the first sign of a goliath

Bingo

**Comment by TheFakeElon** [comment]
Should put MKA under mining tech, doesn’t need its own node.

**Comment by jbox144** [comment]
> Should put MKA under mining tech, doesn’t need its own node.

Kinda has to be, else I'd have conflicts with base tech nodes. ***ModULarE***

**Comment by TheFakeElon** [comment]
You’re allowed to do that, just use our note formatting to indicate the change

**Comment by jbox144** [comment]
wait seriously?

How would I do that?

**Comment by jbox144** [comment]
> Should put MKA under mining tech, doesn’t need its own node.

It's also so you can't pick it up early, lest I hear the cries of "It's to OP"

**Comment by TheFakeElon** [comment]
> wait seriously?
> 
> How would I do that?

Make your change to the line and add “//austation — mech KPA” at the end of it :)

**Comment by TheFakeElon** [comment]
And getting it that much earlier won’t make it OP, just means you don’t have to waste points on a node that gives one item

**Comment by jbox144** [comment]
man I suck at this

**Pull request merged**
