### PR TITLE
Undoing previous cult nerfs

### PR DESCRIPTION
**Pull request by Undeathlol**
## About The Pull Request
I was asked to revert old cult nerfs, adding back armour across the board and buffing weapons back to what they were before.  

## Why It's Good For The Game
No one asked for the nerfs and others wished it returned

## Changelog
:cl:
Balance: Ritual dagger throw force increased back to 25
Balance: Cult swords now deal brute to non cult instead of stamina and brain damage
Balance: Armours buffed across the board
Balance: Mirror shield buffed; recharges illusions, doesn't shatter
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
AARGHHH. modularise your PR please :3

**Comment by ZombiesVsPlants** [comment]
My man!

**Comment by Undeathlol** [comment]
how?

**Comment by amidoingitright** [comment]
basically move bloodcult to austation and put the relevant files into the includes file

**Comment by amidoingitright** [comment]
which will cause conflict errors upon conflict errors if bee decides to change bloodcult

**Comment by MCterra10** [comment]
while I do agree with this, I think the changes are a bit messy to handle. if they're small changes, just comment them in the original code.

**Comment by amidoingitright** [comment]
holy shit you actually did it you madman

**Comment by Undeathlol** [comment]
did i do something wrong?

**Comment by amidoingitright** [comment]
it works and i think its modular

**Comment by TheFakeElon** [comment]
> did i do something wrong?

You didn’t, the override has to be messy because of how much bee changed. So we have to weigh whether it’s worth the _technical debt_

**Comment by MCterra10** [comment]
> 
> 
> > did i do something wrong?
> 
> You didn’t, the override has to be messy because of how much bee changed. So we have to weigh whether it’s worth the _technical debt_

this

**Comment by TheFakeElon** [comment]
blood cult has been doing fine lately anyway. Closing

**Pull request closed without merging**
