### PR TITLE
Anniversary map  (depends on Balloon PR #3342)

### PR DESCRIPTION
**Pull request by Ohagi-Chan**
## About The Pull Request
A testmerge PR that adds PartyStation, which is ludicrously stocked with party balloons and beer.
The Corporate Showroom has been converted into a dark disco area with toggled lights.
Behind the curtains, into command hallway, are plenty of spare party supplies and several crates filled with toys.
Also adds a Balloon Cart to Austation, which I'll readd when this PR is unmerged.

## Why It's Good For The Game
It's our 2nd anniversary of playing AuStation

## Changelog
:cl:
add: Adds PartyStation map
config: PartyStation becomes the default map
/:cl:

### CODE REVIEW

**Comment by Ohagi-Chan** [comment]
this contains all of the commits from #3342 so I hope that doesn't make it a pain to unmerge?

**Comment by TheFakeElon** [comment]
birthday map birthday map

**Comment by Ohagi-Chan** [comment]
in future, instead of adding a separate map, should I just edit Austation.dmm
Since it's only a testmerge anyway?

**Comment by jupyterkat** [comment]
no, then you’ll have to open the pr everytime there’s an anniversary

**Comment by Ohagi-Chan** [comment]
> no, then you’ll have to open the pr everytime there’s an anniversary

That's one way of looking at it, but I don't maintain my event maps.  By the time we reach the 3rd anniversary, AuStation.dmm might look quite different.

**Comment by jupyterkat** [comment]
Eh, someone has to edit it in anyways when it comes. Or you can set the baloon items and stuff to spawn randomly throughout the station instead of editing the map itself.

**Comment by MCterra10** [comment]
party map served its purpose. closing now :)

**Pull request closed without merging**
