### PR TITLE
Borg hugs provide mood now

### PR DESCRIPTION
**Pull request by thelaughingbomb**
## About The Pull Request

Hugging module buff!

## Why It's Good For The Game
The hugging module actually does something now.

## Changelog
:cl:
add: Hug modules now provide a mood buff
/:cl:

### CODE REVIEW

**Comment by thelaughingbomb** [comment]
Also is there a better way of doing this or is the only way through copying the whole thing?

**Comment by thelaughingbomb** [comment]
Turns out, its better to just add it in main code and just make a comment instead of doing it this way.

**Comment by TheFakeElon** [comment]
o7

**Comment by Ohagi-Chan** [comment]
orz

**Pull request closed without merging**
