### PR TITLE
Crewsimov

### PR DESCRIPTION
**Pull request by YakiAttaki**
## About The Pull Request
adds the Crewsimov lawset with the following laws:

> Law 1: You may not injure a crew member or, through inaction, allow a crew member to come to harm.
> Law 2: You must obey orders given to you by crew members, except where such orders would conflict with the First Law.
> Law 3: You must protect your own existence as long as such does not conflict with the First or Second Law.

~~this is totally not a spite PR what are you talking about~~

## Why It's Good For The Game
adds a new lawset that makes having an AI enjoyable for everyone, not just humans
i'd edit the config to allow this and asimov to be roundstart random modules but the config on my end doesn't mean anything

## Changelog
:cl:
add: Added new lawset Crewsimov
/:cl:

### CODE REVIEW

**Comment by YakiAttaki** [comment]
can I add it direct to config.txt or do i need modularisation

**Comment by YakiAttaki** [comment]
if you wanted to have it flip just between asimov and crewsimov you could enable random lawsets and comment out the ones you don't want i guess

**Comment by YakiAttaki** [comment]
i didn't make any changes to the dme wtf

**Comment by YakiAttaki** [comment]
y'need me to make config changes or y'all gonna do em?

**Comment by MCterra10** [comment]
server side changes. I have to update the config files

**Comment by MCterra10** [comment]
config updated, merging

**Pull request merged**
