### PR TITLE
Adds kelvin to medical scanner

### PR DESCRIPTION
**Pull request by thelaughingbomb**
## About The Pull Request

Title

## Why It's Good For The Game

Adds kelvin to the medical scanner, kelvin is used basically everywhere for measuring temp so it seems fitting to add it to the scanner.

## Changelog
:cl:
add: Medical scanner now outputs kelvin aswell
/:cl:

### CODE REVIEW

**Comment by Mick1299** [comment]
So it now has three seperate temperatures? Just make it Celcius with Kelvin in brackets

**Comment by thelaughingbomb** [comment]
I'm keeping Fahrenheit in case there are actually players who can only read Fahrenheit.

**Comment by thelaughingbomb** [comment]
All though, i cant think of a instance in game other then the medical scanner where Fahrenheit is used...

**Comment by thelaughingbomb** [comment]
Decided to nuke the two instances of Fahrenheit, which was the medical scanner and the Odysseus onboard sleeper.

**Comment by totallynotkatfood** [comment]
Fahrenheit is gay

**Comment by TheFakeElon** [comment]
So many whitespaces

**Comment by thelaughingbomb** [comment]
Yeah i dunno where those spaces came from, or why i am lacking them.

**Comment by thelaughingbomb** [comment]
Will check now

**Comment by thelaughingbomb** [comment]
Nanite and PAI give out identical readings like a health analyzer.

**Pull request merged**
