### PR TITLE
[MIRROR] [Port] Cat AI Core

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/6147
--------------------
## About The Pull Request

Ports: https://github.com/yogstation13/Yogstation/pull/8058

aicat

## Why It's Good For The Game

Look at him go

## Changelog
:cl:
imageadd: Added a new AI core display, the Cat
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
causing an issue related to #4610, needs a fix

**Comment by TheFakeElon** [comment]
unmodular icon moment

**Comment by MCterra10** [comment]
remirror

**Comment by MCterra10** [comment]
reverted the other PR, I'll do something about making it modular

**Pull request merged**
