### PR TITLE
Magic defense

### PR DESCRIPTION
**Pull request by amidoingitright**
## About The Pull Request

Gives the chap armor magic defense

## Why It's Good For The Game

The rod is hit and miss with its magic defense, making the armor immune makes sense and also helps boost the lacking with the rod, and makes the unarmoured chaplain clothes resistant to magic as a quasi rebalance

## Changelog
:cl:
Tweak: Gave all chaplain armour magic defense
/:cl:

### CODE REVIEW

**Comment by Mick1299** [comment]
That's a pretty massive chaplain buff

**Comment by MCterra10** [comment]
I'm
Not sure actually
Perhaps it might help rebalance lowpop wiz?

**Comment by TheFakeElon** [comment]
this can be modularised

**Review by TheFakeElon — CHANGES_REQUESTED** [review]
this can be modularised

**Comment by amidoingitright** [comment]
travis seems to be spazzing out

**Comment by amidoingitright** [comment]
Fixed and modularised

**Comment by TheFakeElon** [comment]
it's not modularised, there is no new code in the austation folder. you also managed to delete a beestation DME entry lmao

**Comment by MCterra10** [comment]
closing. feel free to re-open if you modularize stuff

**Pull request closed without merging**
