### PR TITLE
Maint pool runtime fix

### PR DESCRIPTION
**Pull request by totallynotkatfood**
## About The Pull Request

title

## Why It's Good For The Game

Added a CAN_BE_DIRTY_1 flag to the pool to prevent dirt and oil from spawning in the pool turf

## Changelog
:cl:
fix: fixed pool runtime
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
wasn't the runtime fixed in #2028?

**Comment by totallynotkatfood** [comment]
It didn’t fix it, unfortunately. I don’t even know what errored.

**Comment by totallynotkatfood** [comment]
It didn’t fix it, unfortunately

**Comment by totallynotkatfood** [comment]
misclick smh

**Comment by MCterra10** [comment]
I already fixed this kat
The link range wasn't high enough on the controller, so the controller var on the pool tiles was null

**Comment by totallynotkatfood** [comment]
Then why is it still runtimeing after that?

**Comment by TheFakeElon** [comment]
> Then why is it still runtimeing after that?

What PR is that log from?

**Comment by MCterra10** [comment]
I made the fix after your fix pr. It was part of another pr if I recall

**Comment by MCterra10** [comment]
Ohhhh, wheeeeeeze
My fix is part of the bread pr

**Comment by totallynotkatfood** [comment]
080A928C-3BDE-48B7-B65A-2807F112B8A7

**Comment by totallynotkatfood** [comment]
nope, your fix didn’t work it seems

**Comment by totallynotkatfood** [comment]
the runtime only appears when the pool is spawned

**Pull request closed without merging**
