### PR TITLE
Removes AI and borg upload from techweb

### PR DESCRIPTION
**Pull request by TheFakeElon**
## About The Pull Request

Removes AI and Borg upload boards from RnD techweb

## Why It's Good For The Game

It was WAY too easy to subvert the AI/Borgs. Now antags need to actually risk themselves stealing the board from secure tech

## Changelog
:cl:
balance: removes silicon upload boards from techweb
/:cl:

### CODE REVIEW

**Comment by MCterra10** [comment]
also your change log in malformed.
please enclose it with `:cl:` and `/:cl:` on lines before and after your changelog entry, respectively

**Comment by coolsurf6** [comment]
Hmmmmmmmmmmmmm fuck. Can say it was way too easy. Before rebase, it costed diamonds to make, not it doesn't. I think this is better but just means I get to hack into more places rather than make the boards myself.

**Comment by TheFakeElon** [comment]
CL fixed

**Comment by thelaughingbomb** [comment]
The good thing about this change is that it makes only two ways to change laws, from the upload that is pre-built and the board. Downside is that if AI gets subverted the easy solution to just print a upload to reset their laws is no longer available. Which i guess if the antag runs the risk of getting the board, their reward is an AI that is much harder to reset. Guess that makes upload board a "high risk item" now?

**Comment by BeloneX** [comment]
today i will break the upload console and the AI laws cant ever be changed again

**Comment by TheFakeElon** [comment]
> today i will break the upload console and the AI laws cant ever be changed again

Secure tech storage...?
IF they managed to steal the board AND deconstruct the main upload console without getting captured... bravo

**Comment by coolsurf6** [comment]
> Secure tech storage...?
> IF they managed to steal the board AND deconstruct the main upload console without getting captured... bravo

Is that supposed to be a challenge? Door can be broken into in like 15 seconds.

**Comment by MCterra10** [comment]
we'll give it a try. Unlike /tg/, I'm happy to revert if the change ends up being a negative

**Comment by YakiAttaki** [comment]
time to delete all ai boards at the start of the round and pump the AI with terrible ion laws

**Comment by coolsurf6** [comment]
Like I agree with the fact that subverting ai is too easy. I think increasing the price of the upload console alot, as well as the freeform and those modules would be a better idea.

**Pull request merged**
