### PR TITLE
Added Bruh Moment event [MEME PR]

### PR DESCRIPTION
**Pull request by coolsurf6**
Added an event that makes all players emote bruh on the server. This includes other mobs like monkeys, even beepsky etc. The event can be activated using Fun > Trigger Event just like a normal event, and will have a few second delay before the bruhspace anomaly will activate, causing everyone on the station to start emitting bruhs. Only those in the vacinity of another player can hear other bruh though, unlike the original PR where the entire chat would be filled with people going Bruh on the radio. There is a delay of 0.2 seconds between each bruh. This can be tweaked but even with 100 entities on 1 square saying bruh, it doesn't lag. 

This really be a bruh moment.

:cl: 
add: Added Bruh Moment Event. 
/:cl:

### CODE REVIEW

**Comment by thelaughingbomb** [comment]
bruh

**Comment by TheFakeElon** [comment]
bruh

**Comment by coolsurf6** [comment]
bruh

**Comment by BowStache** [comment]
*bruh

**Pull request merged**
