### PR TITLE
[MIRROR] [PORT] Limit how often you can use the emergency shuttle console

### PR DESCRIPTION
**Pull request by AustationBot**
Original PR: https://github.com/BeeStation/BeeStation-Hornet/pull/3175
--------------------

## About The Pull Request

implements https://github.com/tgstation/tgstation/pull/52522/commits/688406f878fae1730d37e89f70291c48f47c9cfa

and

https://github.com/tgstation/tgstation/pull/52522/commits/adec073d06417649fd3a850e54a5b601cb763bec

from https://github.com/tgstation/tgstation/pull/52522

Credit to @ Jared-Fogle 

You can now only use the emergency shuttle console once per 5 seconds.

## Why It's Good For The Game
image

Prevents obnoxious spam of the console.

https://www.youtube.com/watch?v=0g3ZRS7Ev7w

## Changelog
:cl:
tweak: You can now only use the emergency shuttle console once per 5 seconds.
/:cl:

### CODE REVIEW

**Comment by TheFakeElon** [comment]
remirror

**Comment by TheFakeElon** [comment]
For every newline conflict I have to fix, an australian catgirl gf dies

**Comment by jupyterkat** [comment]
*brown catgirl gf

**Comment by TheFakeElon** [comment]
😳

**Comment by jupyterkat** [comment]
😳

**Pull request merged**
