### PR TITLE
Reskinable tiles

### PR DESCRIPTION
**Pull request by jbox144**
## About The Pull Request

Allows you to use tiles in hand to reskin them, allowing for a bit more decorative flare when constructing your space stations.

Also featuring: Another radial

## Why It's Good For The Game

It's a nice touch to allow for more creativity when constructing.

## Changelog
:cl:
add: Added the ability to reskin tiles
/:cl:

### CODE REVIEW

**Comment by jupyterkat** [comment]
floor painters are already a thing. stop reinventing the wheel

**Comment by amidoingitright** [comment]
we are just putting it on something that isn't a model T kat

**Comment by MCterra10** [comment]
> 
> 
> floor painters are already a thing. stop reinventing the wheel

yeah I don't get the point, floor painters are freely available and let you change the skin of placed tiles at zero cost

**Comment by TheFakeElon** [comment]
You're lucky I happened to lurk on /tg/ last year

https://github.com/tgstation/tgstation/pull/54184

**Comment by TheFakeElon** [comment]
You _must_ credit PRs when you port them, you didn't even state that this was a port. Code stealing is really bad practice and makes us look really bad. This is grounds for an instant close but I'll let you off if you _fully_ credit /tg/ in the PR description, code and commits.

**Review by TheFakeElon — CHANGES_REQUESTED** [review]
above

**Comment by MCterra10** [comment]
closing. pr is pointless because of floor painters, and is also an uncredited port

**Pull request closed without merging**
